export interface PageData {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  keyword: string;
  features: { icon: string; title: string; desc: string }[];
  faq: { q: string; a: string }[];
}

export const pagesData: PageData[] = [
  {
    slug: "taxi-executivo-umuarama",
    keyword: "táxi executivo em Umuarama",
    title: "Táxi Executivo Umuarama",
    metaTitle: "Táxi Executivo em Umuarama | Giroto Táxi — Alto Padrão 24h",
    metaDescription: "Táxi executivo em Umuarama com veículos de alto padrão. Ideal para reuniões, eventos corporativos e viagens com conforto e pontualidade. Chame agora!",
    h1: "Táxi Executivo em Umuarama — Alto Padrão e Pontualidade",
    intro: "O táxi executivo em Umuarama da Giroto Táxi é a escolha certa para quem precisa de transporte sofisticado, pontual e discreto. Veículos premium, motoristas profissionais e atendimento impecável para executivos, eventos corporativos e ocasiões especiais.",
    features: [
      { icon: "💼", title: "Veículos Premium", desc: "Frota de alto padrão, climatizada e impecável para o seu conforto." },
      { icon: "⏰", title: "Pontualidade Garantida", desc: "Chegamos no horário combinado, sempre. Ideal para reuniões e voos." },
      { icon: "🤫", title: "Discrição Total", desc: "Serviço discreto e profissional para executivos e pessoas públicas." },
      { icon: "📋", title: "Nota Fiscal", desc: "Emitimos nota fiscal para reembolso corporativo." },
    ],
    faq: [
      { q: "O táxi executivo em Umuarama funciona 24 horas?", a: "Sim! Nosso serviço de táxi executivo em Umuarama opera 24 horas por dia, 7 dias por semana, incluindo feriados." },
      { q: "Posso agendar o táxi executivo com antecedência?", a: "Sim, recomendamos agendar via WhatsApp informando data, horário e destino para garantirmos o melhor atendimento." },
      { q: "O táxi executivo aceita cartão corporativo?", a: "Sim, aceitamos cartão de crédito, débito, Pix e dinheiro. Também emitimos nota fiscal para reembolso." },
    ],
  },
  {
    slug: "taxi-aeroporto-umuarama",
    keyword: "táxi para aeroporto em Umuarama",
    title: "Táxi para Aeroporto Umuarama",
    metaTitle: "Táxi para Aeroporto em Umuarama | Traslado Pontual — Giroto Táxi",
    metaDescription: "Táxi para aeroporto em Umuarama e traslado para o Aeroporto de Maringá. Pontualidade garantida, motorista aguardando. Chame pelo WhatsApp!",
    h1: "Táxi para Aeroporto em Umuarama — Traslado Pontual e Seguro",
    intro: "Precisa de táxi para o aeroporto em Umuarama ou traslado para o Aeroporto Regional de Maringá? A Giroto Táxi garante pontualidade total no seu embarque. Informe o horário do voo e chegue com tranquilidade ao check-in.",
    features: [
      { icon: "✈️", title: "Traslado para Maringá", desc: "Transporte direto de Umuarama para o Aeroporto Regional de Maringá." },
      { icon: "⏰", title: "Pontualidade no Embarque", desc: "Chegamos com antecedência para você não perder o voo." },
      { icon: "🧳", title: "Espaço para Bagagem", desc: "Veículos com porta-malas espaçoso para todas as suas malas." },
      { icon: "📱", title: "Agendamento Fácil", desc: "Agende pelo WhatsApp informando horário do voo e local de embarque." },
    ],
    faq: [
      { q: "Fazem traslado de Umuarama para o aeroporto de Maringá?", a: "Sim! Realizamos traslados frequentes de Umuarama para o Aeroporto Regional de Maringá, com pontualidade garantida." },
      { q: "Com quanto tempo de antecedência devo agendar o táxi para o aeroporto?", a: "Recomendamos agendar com pelo menos 24 horas de antecedência, especialmente para voos matinais." },
      { q: "O táxi espera em caso de atraso do voo?", a: "Sim, monitoramos os voos e nos adaptamos a eventuais atrasos. Entre em contato pelo WhatsApp para atualizações." },
    ],
  },
  {
    slug: "taxi-rodoviaria-umuarama",
    keyword: "táxi para rodoviária de Umuarama",
    title: "Táxi para Rodoviária Umuarama",
    metaTitle: "Táxi para Rodoviária de Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi para a rodoviária de Umuarama 24 horas. Chegue no horário certo para pegar seu ônibus. Atendimento imediato pelo WhatsApp!",
    h1: "Táxi para a Rodoviária de Umuarama — Rápido e Pontual",
    intro: "Não perca seu ônibus! O táxi para a rodoviária de Umuarama da Giroto Táxi garante que você chegue no horário certo, sem estresse. Atendemos 24 horas, inclusive de madrugada para os primeiros ônibus do dia.",
    features: [
      { icon: "🚌", title: "Para Todos os Horários", desc: "Atendemos saídas de madrugada, manhã, tarde e noite para a rodoviária." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista chega em minutos para não atrasar sua viagem." },
      { icon: "🧳", title: "Espaço para Bagagem", desc: "Veículos com porta-malas espaçoso para bagagens de viagem." },
      { icon: "📍", title: "Busca em Qualquer Bairro", desc: "Buscamos você em qualquer bairro de Umuarama." },
    ],
    faq: [
      { q: "O táxi para a rodoviária funciona de madrugada?", a: "Sim! A Giroto Táxi atende 24 horas, inclusive de madrugada para os primeiros ônibus." },
      { q: "Posso agendar o táxi para a rodoviária?", a: "Sim, recomendamos agendar pelo WhatsApp para garantir o veículo no horário certo." },
      { q: "O táxi busca na rodoviária também?", a: "Sim! Fazemos busca na rodoviária de Umuarama para quem chega de viagem." },
    ],
  },
  {
    slug: "taxi-7-lugares-umuarama",
    keyword: "táxi 7 lugares em Umuarama",
    title: "Táxi 7 Lugares Umuarama",
    metaTitle: "Táxi 7 Lugares em Umuarama | Van para Grupos e Famílias — Giroto Táxi",
    metaDescription: "Táxi 7 lugares em Umuarama para grupos e famílias. Espaço de sobra para bagagem e passageiros. Ideal para viagens, eventos e passeios. Chame agora!",
    h1: "Táxi 7 Lugares em Umuarama — Para Toda a Família e Grupos",
    intro: "O táxi 7 lugares em Umuarama da Giroto Táxi é a solução perfeita para famílias, grupos de amigos ou equipes que precisam viajar juntos. Espaço de sobra para passageiros e bagagem, com todo o conforto que você merece.",
    features: [
      { icon: "👨‍👩‍👧‍👦", title: "Até 6 Passageiros", desc: "Capacidade para toda a família viajar junta com conforto." },
      { icon: "🧳", title: "Porta-Malas Amplo", desc: "Espaço generoso para bagagens, mesmo em viagens longas." },
      { icon: "❄️", title: "Ar-Condicionado", desc: "Veículo climatizado para viagens confortáveis em qualquer época." },
      { icon: "🛣️", title: "Viagens Intermunicipais", desc: "Ideal para grupos que viajam para Maringá, Cascavel e toda a região." },
    ],
    faq: [
      { q: "Quantas pessoas cabem no táxi 7 lugares de Umuarama?", a: "Nosso veículo 7 lugares acomoda até 6 passageiros confortavelmente, além do motorista." },
      { q: "O táxi 7 lugares faz viagens intermunicipais?", a: "Sim! É ideal para grupos que viajam para Maringá, Cianorte e toda a região noroeste do Paraná." },
      { q: "Como agendar o táxi 7 lugares em Umuarama?", a: "Basta chamar pelo WhatsApp informando o número de passageiros, destino e horário desejado." },
    ],
  },
  {
    slug: "taxi-cadeirinha-umuarama",
    keyword: "táxi com cadeirinha em Umuarama",
    title: "Táxi com Cadeirinha Umuarama",
    metaTitle: "Táxi com Cadeirinha em Umuarama | Segurança para Crianças — Giroto Táxi",
    metaDescription: "Táxi com cadeirinha infantil em Umuarama. Transporte seguro para bebês e crianças com cadeira homologada. Agende pelo WhatsApp!",
    h1: "Táxi com Cadeirinha em Umuarama — Segurança Total para seu Filho",
    intro: "A segurança do seu filho é a nossa prioridade. O táxi com cadeirinha em Umuarama da Giroto Táxi oferece cadeiras infantis homologadas e adequadas para cada faixa etária. Transporte seu bebê ou criança com total tranquilidade.",
    features: [
      { icon: "👶", title: "Cadeirinha Homologada", desc: "Cadeiras infantis aprovadas pelo INMETRO para máxima segurança." },
      { icon: "🛡️", title: "Para Todas as Idades", desc: "Bebê conforto, cadeirinha e booster conforme a idade da criança." },
      { icon: "😊", title: "Motoristas Treinados", desc: "Profissionais com experiência no transporte de crianças." },
      { icon: "📱", title: "Informe com Antecedência", desc: "Avise a idade da criança ao agendar para prepararmos a cadeirinha ideal." },
    ],
    faq: [
      { q: "O táxi com cadeirinha em Umuarama funciona 24 horas?", a: "Sim! Atendemos 24 horas. Recomendamos agendar com antecedência para garantir a cadeirinha adequada." },
      { q: "Que tipo de cadeirinha vocês têm?", a: "Temos bebê conforto, cadeirinha e booster. Informe a idade da criança ao agendar para prepararmos a cadeira certa." },
      { q: "Posso trazer minha própria cadeirinha?", a: "Sim! Se preferir usar sua própria cadeirinha, nossos motoristas ajudam na instalação." },
    ],
  },
  {
    slug: "taxi-pet-umuarama",
    keyword: "táxi pet em Umuarama",
    title: "Táxi Pet Umuarama",
    metaTitle: "Táxi Pet em Umuarama | Transporte de Animais — Giroto Táxi",
    metaDescription: "Táxi pet em Umuarama para transporte de cães, gatos e outros animais. Veículo preparado e motorista atencioso. Agende pelo WhatsApp!",
    h1: "Táxi Pet em Umuarama — Transporte Seguro para seu Animal",
    intro: "Seu pet também merece conforto e segurança! O táxi pet em Umuarama da Giroto Táxi transporta cães, gatos e outros animais com todo o cuidado necessário. Ideal para consultas veterinárias, banho e tosa, ou mudanças.",
    features: [
      { icon: "🐕", title: "Cães e Gatos", desc: "Transportamos pets de todos os portes com segurança e carinho." },
      { icon: "🏥", title: "Veterinário e Tosa", desc: "Ideal para levar seu pet a consultas, vacinas e banho e tosa." },
      { icon: "🧹", title: "Veículo Preparado", desc: "Carro higienizado e preparado para o transporte de animais." },
      { icon: "❤️", title: "Motoristas Pet Friendly", desc: "Nossa equipe ama animais e trata seu pet com todo o cuidado." },
    ],
    faq: [
      { q: "Posso levar meu cachorro no táxi em Umuarama?", a: "Sim! Nossa Giroto Táxi aceita pets. Recomendamos o uso de caixinha de transporte ou guia para maior segurança." },
      { q: "Há custo adicional para transporte de pet?", a: "Consulte o valor via WhatsApp. Dependendo do porte do animal, pode haver um pequeno adicional." },
      { q: "Transportam animais para clínicas veterinárias de Umuarama?", a: "Sim! Atendemos todas as clínicas e pet shops de Umuarama e região." },
    ],
  },
  {
    slug: "taxi-hospital-umuarama",
    keyword: "táxi para hospital em Umuarama",
    title: "Táxi para Hospital Umuarama",
    metaTitle: "Táxi para Hospital em Umuarama | Atendimento 24h — Giroto Táxi",
    metaDescription: "Táxi para hospital em Umuarama 24 horas. Transporte rápido e seguro para emergências, consultas e exames. Chame agora pelo WhatsApp!",
    h1: "Táxi para Hospital em Umuarama — Rápido em Toda Emergência",
    intro: "Em momentos de urgência médica, cada minuto conta. O táxi para hospital em Umuarama da Giroto Táxi está disponível 24 horas por dia, inclusive de madrugada, para levar você ou sua família com rapidez e segurança a qualquer hospital ou clínica da cidade.",
    features: [
      { icon: "🚑", title: "Atendimento de Emergência", desc: "Disponível 24h para situações urgentes, inclusive de madrugada." },
      { icon: "🏥", title: "Todos os Hospitais", desc: "Atendemos Hospital Umuarama, UPA e todas as clínicas da cidade." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista mais próximo despachado imediatamente para sua localização." },
      { icon: "❤️", title: "Condução com Cuidado", desc: "Motoristas treinados para conduzir com segurança em situações delicadas." },
    ],
    faq: [
      { q: "O táxi para hospital em Umuarama atende de madrugada?", a: "Sim! Atendemos 24 horas por dia, 7 dias por semana, inclusive em emergências de madrugada." },
      { q: "Atendem o Hospital Umuarama e a UPA?", a: "Sim! Atendemos todos os hospitais e clínicas de Umuarama, incluindo o Hospital Umuarama e a UPA." },
      { q: "Posso agendar consultas regulares?", a: "Sim! Muitos clientes usam nosso táxi regularmente para consultas médicas, exames e tratamentos." },
    ],
  },
  {
    slug: "taxi-umuarama-maringa",
    keyword: "táxi de Umuarama para Maringá",
    title: "Táxi de Umuarama para Maringá",
    metaTitle: "Táxi de Umuarama para Maringá | Giroto Táxi — Viagem Segura",
    metaDescription: "Táxi de Umuarama para Maringá com conforto e segurança. Traslado para aeroporto, consultas médicas e negócios. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Maringá — Viagem Confortável e Segura",
    intro: "O táxi de Umuarama para Maringá da Giroto Táxi é a opção mais confortável para quem precisa se deslocar entre as duas cidades. Ideal para consultas médicas, reuniões de negócios, aeroporto e compras. Preço fechado e sem surpresas.",
    features: [
      { icon: "🛣️", title: "Rota Umuarama-Maringá", desc: "Percurso de aproximadamente 130km com motorista experiente na rota." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente, sem taxímetro surpresa na chegada." },
      { icon: "✈️", title: "Aeroporto de Maringá", desc: "Traslado direto para o Aeroporto Regional de Maringá." },
      { icon: "🏥", title: "Hospital de Maringá", desc: "Transporte para consultas e tratamentos médicos em Maringá." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Maringá?", a: "O valor é combinado previamente. Entre em contato pelo WhatsApp para um orçamento rápido e sem compromisso." },
      { q: "Quanto tempo leva a viagem de Umuarama para Maringá?", a: "A viagem leva aproximadamente 1h30 a 2 horas dependendo das condições da estrada." },
      { q: "Fazem viagem de ida e volta Umuarama-Maringá?", a: "Sim! Oferecemos viagem de ida e volta com desconto. Consulte pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-umuarama-cianorte",
    keyword: "táxi de Umuarama para Cianorte",
    title: "Táxi de Umuarama para Cianorte",
    metaTitle: "Táxi de Umuarama para Cianorte | Giroto Táxi — Viagem Segura",
    metaDescription: "Táxi de Umuarama para Cianorte com conforto e preço justo. Viagem segura para consultas, negócios e passeios. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Cianorte — Conforto na Estrada",
    intro: "Precisa viajar de Umuarama para Cianorte? A Giroto Táxi oferece transporte confortável e seguro entre as duas cidades, com preço fechado e motorista experiente na rota. Ideal para consultas, negócios e passeios.",
    features: [
      { icon: "🛣️", title: "Rota Direta", desc: "Viagem direta de Umuarama para Cianorte sem paradas desnecessárias." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente, sem surpresas." },
      { icon: "🕐", title: "Horário Flexível", desc: "Viajamos no horário que for melhor para você." },
      { icon: "↩️", title: "Ida e Volta", desc: "Organizamos viagem de ida e volta com desconto especial." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Cianorte?", a: "Entre em contato pelo WhatsApp para um orçamento rápido. Trabalhamos com preço fechado." },
      { q: "Fazem viagem de ida e volta?", a: "Sim! Com desconto especial para ida e volta. Consulte pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-umuarama-goioere",
    keyword: "táxi de Umuarama para Goioerê",
    title: "Táxi de Umuarama para Goioerê",
    metaTitle: "Táxi de Umuarama para Goioerê | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Goioerê com segurança e conforto. Preço fechado e motorista experiente. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Goioerê — Viagem Tranquila",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Goioerê com conforto, segurança e preço justo. Motorista experiente na rota e preço fechado combinado previamente.",
    features: [
      { icon: "🛣️", title: "Rota Direta", desc: "Viagem direta sem paradas desnecessárias." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente, sem surpresas." },
      { icon: "↩️", title: "Ida e Volta", desc: "Viagem de ida e volta com desconto especial." },
      { icon: "📱", title: "Agendamento Fácil", desc: "Agende pelo WhatsApp com rapidez e praticidade." },
    ],
    faq: [
      { q: "Fazem táxi de Umuarama para Goioerê?", a: "Sim! Realizamos viagens para Goioerê e toda a região noroeste do Paraná." },
      { q: "Como solicitar orçamento?", a: "Basta chamar no WhatsApp informando origem, destino e horário desejado." },
    ],
  },
  {
    slug: "taxi-umuarama-cruzeiro-do-oeste",
    keyword: "táxi de Umuarama para Cruzeiro do Oeste",
    title: "Táxi Umuarama para Cruzeiro do Oeste",
    metaTitle: "Táxi de Umuarama para Cruzeiro do Oeste | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Cruzeiro do Oeste. Viagem confortável com preço fechado. Chame pelo WhatsApp!",
    h1: "Táxi de Umuarama para Cruzeiro do Oeste",
    intro: "Viagens de Umuarama para Cruzeiro do Oeste com a Giroto Táxi. Conforto, segurança e preço justo para seu deslocamento intermunicipal.",
    features: [
      { icon: "🛣️", title: "Rota Direta", desc: "Viagem direta com motorista experiente na rota." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente sem surpresas." },
      { icon: "↩️", title: "Ida e Volta", desc: "Com desconto especial para ida e volta." },
      { icon: "📱", title: "WhatsApp", desc: "Agende com facilidade pelo WhatsApp." },
    ],
    faq: [
      { q: "Fazem viagem para Cruzeiro do Oeste?", a: "Sim! Atendemos Cruzeiro do Oeste e toda a região noroeste do Paraná." },
    ],
  },
  {
    slug: "taxi-centro-umuarama",
    keyword: "táxi no centro de Umuarama",
    title: "Táxi no Centro de Umuarama",
    metaTitle: "Táxi no Centro de Umuarama | Corridas Rápidas — Giroto Táxi",
    metaDescription: "Táxi no centro de Umuarama com atendimento imediato. Corridas rápidas para qualquer ponto da cidade. Chame pelo WhatsApp!",
    h1: "Táxi no Centro de Umuarama — Atendimento Imediato",
    intro: "Precisa de táxi no centro de Umuarama? A Giroto Táxi atende a região central com rapidez e eficiência. Corridas para comércio, bancos, cartórios, fóruns e qualquer ponto do centro de Umuarama.",
    features: [
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista próximo ao centro despachado imediatamente." },
      { icon: "🏪", title: "Para Todo o Comércio", desc: "Bancos, cartório, fórum, lojas e qualquer ponto do centro." },
      { icon: "🅿️", title: "Sem Problema de Estacionamento", desc: "Esqueça a busca por vaga. Deixe o motorista resolver." },
      { icon: "📱", title: "Chame pelo WhatsApp", desc: "Um clique e o táxi está a caminho." },
    ],
    faq: [
      { q: "O táxi do centro de Umuarama funciona nos fins de semana?", a: "Sim! Atendemos 7 dias por semana, 24 horas por dia." },
      { q: "Fazem corridas dentro do centro de Umuarama?", a: "Sim! Atendemos qualquer trecho, mesmo curto, dentro do centro de Umuarama." },
    ],
  },
  {
    slug: "taxi-noturno-umuarama",
    keyword: "táxi noturno em Umuarama",
    title: "Táxi Noturno Umuarama",
    metaTitle: "Táxi Noturno em Umuarama | Disponível de Madrugada — Giroto Táxi",
    metaDescription: "Táxi noturno em Umuarama disponível de madrugada, fins de semana e feriados. Volte de festas e eventos com segurança. Chame agora!",
    h1: "Táxi Noturno em Umuarama — Segurança na Madrugada",
    intro: "O táxi noturno em Umuarama da Giroto Táxi garante sua segurança nas saídas de festas, bares, restaurantes e eventos. Disponível durante toda a madrugada, fins de semana e feriados. Não dirija após beber — chame a Giroto Táxi.",
    features: [
      { icon: "🌙", title: "Disponível 24h", desc: "Atendemos em qualquer horário da noite e madrugada." },
      { icon: "🍻", title: "Saída de Festas", desc: "Volte com segurança de bares, festas e eventos noturnos." },
      { icon: "🎉", title: "Finais de Semana", desc: "Disponível sextas, sábados e domingos em todos os horários." },
      { icon: "🛡️", title: "Sua Segurança", desc: "Não arrisque. Chame nosso táxi e chegue em casa com segurança." },
    ],
    faq: [
      { q: "O táxi noturno de Umuarama funciona de madrugada?", a: "Sim! Atendemos 24 horas, inclusive madrugada, fins de semana e feriados." },
      { q: "Fazem corridas após festas e eventos em Umuarama?", a: "Sim! É um dos nossos principais serviços noturnos. Chame pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-casamento-umuarama",
    keyword: "táxi para casamento em Umuarama",
    title: "Táxi para Casamento Umuarama",
    metaTitle: "Táxi para Casamento em Umuarama | Transporte de Noivos — Giroto Táxi",
    metaDescription: "Táxi para casamento em Umuarama. Transporte dos noivos, padrinhos e convidados com pontualidade e elegância. Agende pelo WhatsApp!",
    h1: "Táxi para Casamento em Umuarama — Elegância no seu Grande Dia",
    intro: "O seu casamento merece tudo de melhor, incluindo o transporte. A Giroto Táxi oferece serviço especial para casamentos em Umuarama: transporte dos noivos, padrinhos e familiares com pontualidade, elegância e veículos impecáveis.",
    features: [
      { icon: "💍", title: "Transporte dos Noivos", desc: "Chegue ao altar com estilo e pontualidade." },
      { icon: "👗", title: "Para Padrinhos e Família", desc: "Coordenamos o transporte de toda a família e padrinhos." },
      { icon: "✨", title: "Veículos Preparados", desc: "Veículos limpos e impecáveis para o dia especial." },
      { icon: "📅", title: "Agendamento Antecipado", desc: "Reserve com antecedência para garantir disponibilidade no seu dia." },
    ],
    faq: [
      { q: "Fazem transporte para casamentos em Umuarama?", a: "Sim! Oferecemos serviço completo de transporte para casamentos, incluindo noivos, padrinhos e convidados." },
      { q: "Com quanto tempo devo agendar o táxi para o casamento?", a: "Recomendamos agendar com pelo menos 2 semanas de antecedência para garantir disponibilidade." },
    ],
  },
  {
    slug: "taxi-formatura-umuarama",
    keyword: "táxi para formatura em Umuarama",
    title: "Táxi para Formatura Umuarama",
    metaTitle: "Táxi para Formatura em Umuarama | Transporte Especial — Giroto Táxi",
    metaDescription: "Táxi para formatura em Umuarama. Chegue com estilo e pontualidade na sua noite especial. Agende pelo WhatsApp!",
    h1: "Táxi para Formatura em Umuarama — Chegue com Estilo",
    intro: "A noite da formatura é inesquecível. Chegue com estilo e pontualidade com o táxi para formatura em Umuarama da Giroto Táxi. Transporte individual ou em grupo para formaturas de ensino médio, faculdade e pós-graduação.",
    features: [
      { icon: "🎓", title: "Noite Especial", desc: "Transporte impecável para a noite mais importante da sua trajetória acadêmica." },
      { icon: "👔", title: "Veículo Limpo", desc: "Carro higienizado e preparado para ocasiões especiais." },
      { icon: "👥", title: "Individual ou Grupo", desc: "Atendemos formandos individuais ou grupos de amigos." },
      { icon: "📱", title: "Agende com Facilidade", desc: "Reserve pelo WhatsApp com antecedência." },
    ],
    faq: [
      { q: "Fazem transporte para formaturas em Umuarama?", a: "Sim! É um evento especial para nós também. Chegue com estilo na sua formatura." },
    ],
  },
  {
    slug: "taxi-empresas-umuarama",
    keyword: "táxi para empresas em Umuarama",
    title: "Táxi para Empresas Umuarama",
    metaTitle: "Táxi Corporativo em Umuarama | Para Empresas — Giroto Táxi",
    metaDescription: "Táxi corporativo em Umuarama para empresas. Transporte de executivos, clientes e equipes com nota fiscal. Contrate pelo WhatsApp!",
    h1: "Táxi Corporativo em Umuarama — Solução para sua Empresa",
    intro: "A Giroto Táxi oferece soluções de transporte corporativo em Umuarama para empresas de todos os portes. Transporte de executivos, clientes, equipes e visitantes com pontualidade, discrição e nota fiscal.",
    features: [
      { icon: "🏢", title: "Conta Corporativa", desc: "Serviço dedicado para empresas com faturamento mensal." },
      { icon: "📋", title: "Nota Fiscal", desc: "Emitimos nota fiscal para todos os serviços corporativos." },
      { icon: "👔", title: "Executivos e Clientes", desc: "Transporte de diretores, gerentes e clientes VIP." },
      { icon: "📊", title: "Relatório de Corridas", desc: "Relatório mensal de corridas para controle financeiro." },
    ],
    faq: [
      { q: "Vocês atendem empresas em Umuarama?", a: "Sim! Temos conta corporativa para empresas com faturamento mensal e nota fiscal." },
      { q: "Emitem nota fiscal?", a: "Sim! Emitimos nota fiscal para todos os serviços corporativos." },
    ],
  },
  {
    slug: "taxi-nota-fiscal-umuarama",
    keyword: "táxi com nota fiscal em Umuarama",
    title: "Táxi com Nota Fiscal Umuarama",
    metaTitle: "Táxi com Nota Fiscal em Umuarama | Giroto Táxi",
    metaDescription: "Táxi com nota fiscal em Umuarama para reembolso corporativo. Serviço profissional e documentado. Chame pelo WhatsApp!",
    h1: "Táxi com Nota Fiscal em Umuarama — Reembolso Corporativo",
    intro: "Precisa de táxi com nota fiscal em Umuarama para reembolso da empresa? A Giroto Táxi emite nota fiscal para todos os serviços, facilitando o controle financeiro e o reembolso corporativo.",
    features: [
      { icon: "📋", title: "Nota Fiscal Garantida", desc: "Emitimos nota fiscal para todos os serviços solicitados." },
      { icon: "💼", title: "Reembolso Fácil", desc: "Documentação completa para reembolso corporativo." },
      { icon: "🏢", title: "Para Empresas", desc: "Ideal para colaboradores que viajam a trabalho." },
      { icon: "📱", title: "Solicite pelo WhatsApp", desc: "Informe CNPJ ao agendar para emissão da nota." },
    ],
    faq: [
      { q: "Vocês emitem nota fiscal para táxi em Umuarama?", a: "Sim! Emitimos nota fiscal para todos os serviços. Informe o CNPJ ao agendar." },
    ],
  },
  {
    slug: "taxi-idosos-umuarama",
    keyword: "táxi para idosos em Umuarama",
    title: "Táxi para Idosos Umuarama",
    metaTitle: "Táxi para Idosos em Umuarama | Cuidado e Atenção — Giroto Táxi",
    metaDescription: "Táxi para idosos em Umuarama com motoristas pacientes e atentos. Transporte para consultas, farmácias e compromissos. Chame agora!",
    h1: "Táxi para Idosos em Umuarama — Cuidado e Atenção Especial",
    intro: "A Giroto Táxi oferece serviço de táxi para idosos em Umuarama com toda a atenção e paciência que nossos clientes mais experientes merecem. Motoristas gentis, auxílio para entrar e sair do veículo e condução tranquila.",
    features: [
      { icon: "👴", title: "Motoristas Pacientes", desc: "Equipe treinada para atender idosos com gentileza e paciência." },
      { icon: "🤝", title: "Auxílio no Embarque", desc: "Ajudamos na entrada e saída do veículo com segurança." },
      { icon: "🏥", title: "Para Consultas e Exames", desc: "Transporte regular para consultas médicas e exames." },
      { icon: "💊", title: "Para Farmácias", desc: "Corridas rápidas para farmácias e drogarias de Umuarama." },
    ],
    faq: [
      { q: "O táxi para idosos em Umuarama tem atendimento especial?", a: "Sim! Nossa equipe é treinada para atender idosos com paciência, gentileza e auxílio no embarque e desembarque." },
    ],
  },
  {
    slug: "taxi-farmacia-umuarama",
    keyword: "táxi para farmácia em Umuarama",
    title: "Táxi para Farmácia Umuarama",
    metaTitle: "Táxi para Farmácia em Umuarama | Rápido 24h — Giroto Táxi",
    metaDescription: "Táxi para farmácia em Umuarama 24 horas. Atendimento rápido para buscar medicamentos em qualquer horário. Chame pelo WhatsApp!",
    h1: "Táxi para Farmácia em Umuarama — Medicamentos na Hora",
    intro: "Precisa buscar medicamentos de urgência? O táxi para farmácia em Umuarama da Giroto Táxi está disponível 24 horas para levar você ou buscar seus remédios em qualquer farmácia da cidade.",
    features: [
      { icon: "💊", title: "Urgência 24h", desc: "Disponível a qualquer hora para buscar medicamentos urgentes." },
      { icon: "🏪", title: "Todas as Farmácias", desc: "Atendemos Drogasil, Ultrafarma e todas as farmácias de Umuarama." },
      { icon: "⚡", title: "Atendimento Rápido", desc: "Motorista despachado imediatamente para sua localização." },
      { icon: "🌙", title: "Inclusive de Madrugada", desc: "Não deixamos você sem medicamento em nenhum horário." },
    ],
    faq: [
      { q: "O táxi para farmácia em Umuarama funciona de madrugada?", a: "Sim! Atendemos 24 horas, inclusive de madrugada para medicamentos urgentes." },
    ],
  },
  {
    slug: "taxi-supermercado-umuarama",
    keyword: "táxi para supermercado em Umuarama",
    title: "Táxi para Supermercado Umuarama",
    metaTitle: "Táxi para Supermercado em Umuarama | Giroto Táxi",
    metaDescription: "Táxi para supermercado em Umuarama. Faça suas compras sem preocupação com transporte. Chame pelo WhatsApp!",
    h1: "Táxi para Supermercado em Umuarama — Compras sem Preocupação",
    intro: "Faça suas compras no supermercado sem se preocupar com transporte. O táxi para supermercado em Umuarama da Giroto Táxi leva e traz você com conforto, com espaço para suas sacolas.",
    features: [
      { icon: "🛒", title: "Todos os Supermercados", desc: "Atendemos Condor, Muffato e todos os supermercados de Umuarama." },
      { icon: "🛍️", title: "Espaço para Compras", desc: "Porta-malas espaçoso para todas as suas sacolas." },
      { icon: "↩️", title: "Ida e Volta", desc: "Organizamos a viagem de ida e volta para suas compras." },
      { icon: "📱", title: "Agende pelo WhatsApp", desc: "Reserve o horário para não ter espera." },
    ],
    faq: [
      { q: "Fazem táxi para supermercado em Umuarama?", a: "Sim! Atendemos todos os supermercados da cidade com espaço para suas compras." },
    ],
  },
  {
    slug: "taxi-agendado-umuarama",
    keyword: "táxi agendado em Umuarama",
    title: "Táxi Agendado Umuarama",
    metaTitle: "Táxi Agendado em Umuarama | Reserve com Antecedência — Giroto Táxi",
    metaDescription: "Agende seu táxi em Umuarama com antecedência. Garantia de atendimento no horário certo para voos, consultas e compromissos. Chame pelo WhatsApp!",
    h1: "Táxi Agendado em Umuarama — Reserve e Garanta seu Horário",
    intro: "Evite imprevistos agendando seu táxi em Umuarama com antecedência. Ideal para voos, consultas médicas, compromissos importantes e qualquer situação onde a pontualidade é essencial.",
    features: [
      { icon: "📅", title: "Reserve com Antecedência", desc: "Garanta seu táxi no horário exato que precisar." },
      { icon: "⏰", title: "Pontualidade Garantida", desc: "Chegamos no horário combinado, sempre." },
      { icon: "📱", title: "Agendamento pelo WhatsApp", desc: "Agende informando data, horário e destino." },
      { icon: "✅", title: "Confirmação Imediata", desc: "Confirmamos o agendamento na hora pelo WhatsApp." },
    ],
    faq: [
      { q: "Como agendar um táxi em Umuarama?", a: "Basta chamar pelo WhatsApp informando data, horário, local de embarque e destino. Confirmamos imediatamente." },
      { q: "Com quanto tempo de antecedência posso agendar?", a: "Agendamos com qualquer antecedência — desde algumas horas até dias antes." },
    ],
  },
  {
    slug: "taxi-24h-umuarama",
    keyword: "táxi 24h em Umuarama",
    title: "Táxi 24h Umuarama",
    metaTitle: "Táxi 24h em Umuarama | Disponível Sempre — Giroto Táxi",
    metaDescription: "Táxi 24 horas em Umuarama, 7 dias por semana. Atendimento imediato em qualquer horário, inclusive madrugada e feriados. Chame pelo WhatsApp!",
    h1: "Táxi 24h em Umuarama — Sempre Disponível para Você",
    intro: "A Giroto Táxi é o único serviço de táxi 24h em Umuarama que você pode contar em qualquer situação. De madrugada, feriados, fins de semana ou horário de pico — estamos sempre prontos para atender.",
    features: [
      { icon: "🌙", title: "Madrugada", desc: "Disponível em todos os horários da madrugada." },
      { icon: "🎉", title: "Feriados", desc: "Não paramos em feriados nacionais e locais." },
      { icon: "📅", title: "Fins de Semana", desc: "Sábados e domingos com atendimento completo." },
      { icon: "⚡", title: "Resposta Imediata", desc: "Respondemos no WhatsApp em segundos." },
    ],
    faq: [
      { q: "O táxi de Umuarama realmente funciona 24 horas?", a: "Sim! A Giroto Táxi opera 24 horas por dia, 7 dias por semana, 365 dias por ano, sem exceção." },
      { q: "E em feriados nacionais?", a: "Sim! Não paramos em nenhum feriado. Estamos sempre disponíveis." },
    ],
  },
  {
    slug: "taxi-zona1-umuarama",
    keyword: "táxi na Zona 1 de Umuarama",
    title: "Táxi na Zona 1 de Umuarama",
    metaTitle: "Táxi na Zona 1 de Umuarama | Atendimento Rápido — Giroto Táxi",
    metaDescription: "Táxi na Zona 1 de Umuarama com atendimento rápido e seguro. Corridas para qualquer destino 24 horas. Chame pelo WhatsApp!",
    h1: "Táxi na Zona 1 de Umuarama — Rápido e Confiável",
    intro: "Mora ou está na Zona 1 de Umuarama? A Giroto Táxi atende toda a região com rapidez e eficiência. Corridas para o centro, hospitais, rodoviária e qualquer destino 24 horas por dia.",
    features: [
      { icon: "📍", title: "Cobertura Total da Zona 1", desc: "Atendemos todos os bairros e ruas da Zona 1 de Umuarama." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista próximo à Zona 1 despachado imediatamente." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora do dia ou da noite." },
      { icon: "📱", title: "Chame pelo WhatsApp", desc: "Atendimento imediato pelo WhatsApp." },
    ],
    faq: [
      { q: "O táxi atende na Zona 1 de Umuarama?", a: "Sim! Atendemos toda a Zona 1 com rapidez e eficiência, 24 horas por dia." },
    ],
  },
  {
    slug: "taxi-zona2-umuarama",
    keyword: "táxi na Zona 2 de Umuarama",
    title: "Táxi na Zona 2 de Umuarama",
    metaTitle: "Táxi na Zona 2 de Umuarama | Atendimento Rápido — Giroto Táxi",
    metaDescription: "Táxi na Zona 2 de Umuarama 24 horas. Corridas rápidas e seguras para qualquer destino. Chame pelo WhatsApp!",
    h1: "Táxi na Zona 2 de Umuarama — Atendimento Imediato",
    intro: "A Giroto Táxi atende toda a Zona 2 de Umuarama com rapidez, segurança e conforto. Corridas urbanas, viagens intermunicipais e qualquer tipo de transporte 24 horas por dia.",
    features: [
      { icon: "📍", title: "Cobertura Total da Zona 2", desc: "Atendemos todos os bairros da Zona 2 de Umuarama." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista próximo despachado imediatamente." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora." },
      { icon: "📱", title: "WhatsApp", desc: "Chame pelo WhatsApp agora." },
    ],
    faq: [
      { q: "O táxi atende na Zona 2 de Umuarama?", a: "Sim! Atendemos toda a Zona 2 com rapidez, 24 horas por dia." },
    ],
  },
  {
    slug: "taxi-zona3-umuarama",
    keyword: "táxi na Zona 3 de Umuarama",
    title: "Táxi na Zona 3 de Umuarama",
    metaTitle: "Táxi na Zona 3 de Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi na Zona 3 de Umuarama com atendimento 24 horas. Corridas rápidas e seguras. Chame pelo WhatsApp!",
    h1: "Táxi na Zona 3 de Umuarama — Sempre Disponível",
    intro: "Atendemos toda a Zona 3 de Umuarama com eficiência e rapidez. A Giroto Táxi está disponível 24 horas para qualquer tipo de corrida ou viagem.",
    features: [
      { icon: "📍", title: "Cobertura Zona 3", desc: "Atendemos todos os bairros da Zona 3." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista próximo despachado imediatamente." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora." },
      { icon: "📱", title: "WhatsApp", desc: "Chame pelo WhatsApp agora." },
    ],
    faq: [
      { q: "Atendem na Zona 3 de Umuarama?", a: "Sim! Atendemos toda a Zona 3, 24 horas por dia." },
    ],
  },
  {
    slug: "taxi-show-evento-umuarama",
    keyword: "táxi para show e eventos em Umuarama",
    title: "Táxi para Shows e Eventos Umuarama",
    metaTitle: "Táxi para Shows e Eventos em Umuarama | Giroto Táxi",
    metaDescription: "Táxi para shows, eventos e festas em Umuarama. Vá e volte com segurança sem se preocupar com estacionamento. Chame pelo WhatsApp!",
    h1: "Táxi para Shows e Eventos em Umuarama — Vá e Volte com Segurança",
    intro: "Curta o show ou evento sem se preocupar com estacionamento ou dirigir após a festa. O táxi para eventos em Umuarama da Giroto Táxi leva e traz você com segurança e conforto.",
    features: [
      { icon: "🎵", title: "Shows e Festivais", desc: "Transporte para todos os shows e festivais de Umuarama." },
      { icon: "🎪", title: "Expo Umuarama", desc: "Atendimento especial durante a Expo e grandes eventos." },
      { icon: "🍻", title: "Volte com Segurança", desc: "Não dirija após beber. Chame nosso táxi." },
      { icon: "🚗", title: "Sem Estacionamento", desc: "Esqueça a busca por vaga. Deixe conosco." },
    ],
    faq: [
      { q: "Fazem transporte para eventos em Umuarama?", a: "Sim! Atendemos shows, festas e eventos de todos os tipos em Umuarama." },
    ],
  },
  {
    slug: "taxi-umuarama-londrina",
    keyword: "táxi de Umuarama para Londrina",
    title: "Táxi de Umuarama para Londrina",
    metaTitle: "Táxi de Umuarama para Londrina | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Londrina com conforto e segurança. Preço fechado e motorista experiente. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Londrina — Viagem Confortável",
    intro: "Viagens de Umuarama para Londrina com a Giroto Táxi. Conforto, segurança e preço fechado para sua viagem ao norte do Paraná.",
    features: [
      { icon: "🛣️", title: "Rota Direta", desc: "Viagem direta de Umuarama a Londrina." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente sem surpresas." },
      { icon: "↩️", title: "Ida e Volta", desc: "Com desconto especial." },
      { icon: "📱", title: "Agende pelo WhatsApp", desc: "Orçamento rápido e fácil." },
    ],
    faq: [
      { q: "Fazem táxi de Umuarama para Londrina?", a: "Sim! Realizamos viagens para Londrina com preço fechado. Consulte pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-umuarama-campo-mourao",
    keyword: "táxi de Umuarama para Campo Mourão",
    title: "Táxi de Umuarama para Campo Mourão",
    metaTitle: "Táxi de Umuarama para Campo Mourão | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Campo Mourão. Viagem segura com preço fechado. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Campo Mourão",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Campo Mourão com conforto e segurança. Preço fechado e motorista experiente na rota.",
    features: [
      { icon: "🛣️", title: "Rota Direta", desc: "Viagem direta sem paradas." },
      { icon: "💰", title: "Preço Fechado", desc: "Sem surpresas no final." },
      { icon: "↩️", title: "Ida e Volta", desc: "Com desconto especial." },
      { icon: "📱", title: "WhatsApp", desc: "Orçamento pelo WhatsApp." },
    ],
    faq: [
      { q: "Fazem viagem para Campo Mourão?", a: "Sim! Atendemos Campo Mourão e toda a região do Paraná." },
    ],
  },
  {
    slug: "taxi-umuarama-curitiba",
    keyword: "táxi de Umuarama para Curitiba",
    title: "Táxi de Umuarama para Curitiba",
    metaTitle: "Táxi de Umuarama para Curitiba | Giroto Táxi — Longa Distância",
    metaDescription: "Táxi de Umuarama para Curitiba. Viagem longa e confortável com motorista experiente e preço fechado. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Curitiba — Longa Distância com Conforto",
    intro: "Precisa viajar de Umuarama para Curitiba? A Giroto Táxi realiza essa viagem de longa distância com conforto total, motorista descansado e preço fechado sem surpresas.",
    features: [
      { icon: "🛣️", title: "Longa Distância", desc: "Experiência em viagens longas com segurança e conforto." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado previamente." },
      { icon: "☕", title: "Paradas Programadas", desc: "Paradas para descanso e alimentação quando necessário." },
      { icon: "📱", title: "Agende Antecipado", desc: "Reserve com antecedência pelo WhatsApp." },
    ],
    faq: [
      { q: "Fazem táxi de Umuarama para Curitiba?", a: "Sim! Realizamos viagens de longa distância para Curitiba. Consulte o valor pelo WhatsApp." },
    ],
  },
  {
    slug: "chamar-taxi-umuarama",
    keyword: "chamar táxi em Umuarama",
    title: "Chamar Táxi em Umuarama",
    metaTitle: "Chamar Táxi em Umuarama | A Forma Mais Rápida — Giroto Táxi",
    metaDescription: "Como chamar táxi em Umuarama? Pelo WhatsApp ou telefone da Giroto Táxi. Atendimento imediato 24 horas. Chame agora!",
    h1: "Como Chamar Táxi em Umuarama — Rápido pelo WhatsApp",
    intro: "A forma mais rápida de chamar táxi em Umuarama é pelo WhatsApp da Giroto Táxi. Uma mensagem pronta já estará preenchida — é só enviar e aguardar o motorista mais próximo.",
    features: [
      { icon: "📱", title: "Pelo WhatsApp", desc: "A forma mais rápida — clique no botão e envie a mensagem pronta." },
      { icon: "📞", title: "Pelo Telefone", desc: "Ligue para (44) 99891-3040 e fale diretamente com a central." },
      { icon: "⚡", title: "Resposta em Segundos", desc: "Confirmamos o táxi em segundos pelo WhatsApp." },
      { icon: "📍", title: "Informe sua Localização", desc: "Compartilhe onde você está para enviarmos o motorista mais próximo." },
    ],
    faq: [
      { q: "Qual a forma mais rápida de chamar táxi em Umuarama?", a: "Pelo WhatsApp! Clique no botão abaixo e uma mensagem pronta já estará preenchida." },
      { q: "Tem aplicativo de táxi em Umuarama?", a: "Usamos o WhatsApp como nosso canal principal — é mais rápido e direto do que qualquer app." },
    ],
  },
  {
    slug: "corridas-taxi-umuarama",
    keyword: "corridas de táxi em Umuarama",
    title: "Corridas de Táxi em Umuarama",
    metaTitle: "Corridas de Táxi em Umuarama | Rápido e Seguro — Giroto Táxi",
    metaDescription: "Corridas de táxi em Umuarama 24 horas. Transporte rápido e seguro para qualquer destino na cidade. Chame pelo WhatsApp!",
    h1: "Corridas de Táxi em Umuarama — Para Qualquer Destino",
    intro: "A Giroto Táxi realiza corridas de táxi em Umuarama para qualquer destino na cidade. Supermercado, hospital, rodoviária, trabalho, escola — onde você precisar, estamos lá.",
    features: [
      { icon: "🚖", title: "Qualquer Destino", desc: "Atendemos qualquer ponto de Umuarama." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motorista mais próximo despachado imediatamente." },
      { icon: "💳", title: "Pix, Cartão ou Dinheiro", desc: "Todas as formas de pagamento aceitas." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível em qualquer horário." },
    ],
    faq: [
      { q: "Como pagar a corrida de táxi em Umuarama?", a: "Aceitamos Pix, cartão de crédito, débito e dinheiro em espécie." },
      { q: "O valor é pelo taxímetro?", a: "Para corridas urbanas usamos o taxímetro. Para viagens intermunicipais, preço fechado." },
    ],
  },
];

export const footerLinks = pagesData.map(p => ({
  slug: p.slug,
  title: p.title,
}));
