export interface GalleryImage {
  src: string
  alt: string
}

export interface Testimonial {
  nome: string
  bairro: string
  texto: string
}

export interface PageData {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  h1: string
  intro: string
  keyword: string
  features: { icon: string; title: string; desc: string }[]
  faq: { q: string; a: string }[]
  heroImage: GalleryImage
  galleryImages: GalleryImage[]
  testimonials: Testimonial[]
}

const FOTOS = {
  f01: {
    src: "/fotos/f01-corolla-bourbon-executivo.jpg",
    alt: "Toyota Corolla táxi executivo Umuarama na entrada do Hotel Bourbon — Giroto Táxi",
  },
  f02: {
    src: "/fotos/f02-taigun-taxi-7-lugares.jpg",
    alt: "VW Taigun táxi 7 lugares Umuarama nº 86 — Giroto Táxi",
  },
  f03: {
    src: "/fotos/f03-corolla-ponto-maringa.jpg",
    alt: "Corolla táxi nº 167 no ponto de táxi de Maringá PR — Giroto Táxi Umuarama",
  },
  f04: {
    src: "/fotos/f04-yaris-frota-umuarama.jpg",
    alt: "Toyota Yaris táxi frota Umuarama nº 99 — Giroto Táxi",
  },
  f05: {
    src: "/fotos/f05-corolla-aeroporto-maringa.jpg",
    alt: "Táxi Corolla no aeroporto de Maringá PR — traslado saindo de Umuarama Giroto Táxi",
  },
  f06: {
    src: "/fotos/f06-corolla-aeroporto-umuarama.jpg",
    alt: "Corolla táxi no Aeroporto Silvio Name Júnior de Umuarama PR — Giroto Táxi",
  },
  f07: {
    src: "/fotos/f07-corolla-rodoviaria-viagem.jpg",
    alt: "Táxi Corolla saída de rodoviária — viagem de Umuarama para Maringá e Londrina",
  },
  f08: {
    src: "/fotos/f08-corolla-estacionamento.jpg",
    alt: "Toyota Corolla táxi executivo frota 2026 Umuarama — Giroto Táxi",
  },
  f09: {
    src: "/fotos/f09-spin-taxi-familia.jpg",
    alt: "Chevrolet Spin táxi 7 lugares família Umuarama PR — Giroto Táxi",
  },
  f10: {
    src: "/fotos/f10-corolla-rodoviaria-umuarama.jpg",
    alt: "Táxi Corolla na Estação Rodoviária de Umuarama PR — Giroto Táxi 24h",
  },
}

const DEPOIMENTOS_EXECUTIVO = [
  { nome: "Carlos R.", bairro: "Centro", texto: "Precisei de táxi executivo para uma reunião importante em Maringá. O motorista chegou no horário, veículo impecável. Indico para qualquer executivo em Umuarama." },
  { nome: "Fernanda M.", bairro: "Jardim Panorama", texto: "Uso o serviço toda semana para ir ao aeroporto. Pontual, discreto e o carro é sempre limpo. Melhor táxi executivo de Umuarama sem dúvida." },
  { nome: "Ricardo A.", bairro: "Zona I", texto: "Emitem nota fiscal, o que é essencial para reembolso da empresa. Serviço profissional de verdade." },
]

const DEPOIMENTOS_AEROPORTO = [
  { nome: "Patrícia L.", bairro: "Centro", texto: "Já perdi voo uma vez por causa de outro táxi. Com a Giroto nunca aconteceu isso. Monitoram o voo e avisam qualquer alteração. Tranquilidade total." },
  { nome: "Marcos S.", bairro: "Jardim Aratimbó", texto: "Fiz o traslado Umuarama–Maringá várias vezes. Sempre pontual, preço combinado antes, sem surpresa. Recomendo." },
  { nome: "Ana C.", bairro: "Parque Tarumã", texto: "Viajei com três malas e o porta-malas comportou tudo com folga. Motorista prestativo e educado." },
]

const DEPOIMENTOS_RODOVIARIA = [
  { nome: "João P.", bairro: "Zona II", texto: "Cheguei de madrugada na rodoviária e o táxi já estava esperando. Segurança e conforto de verdade." },
  { nome: "Silvia T.", bairro: "Centro", texto: "Uso sempre para ir pegar minha mãe na rodoviária. Pontualidade que você pode confiar." },
  { nome: "Rafael N.", bairro: "Jardim Europa", texto: "Preço justo e honesto. Motorista conhece todas as rotas da cidade." },
]

const DEPOIMENTOS_MARINGA = [
  { nome: "Adriana F.", bairro: "Centro", texto: "Faço tratamento em Maringá toda semana. A Giroto Táxi é minha companheira fiel nessa rota. Confiança total." },
  { nome: "Pedro H.", bairro: "Zona III", texto: "Preço fechado antes da viagem, sem surpresa no final. Saí de Umuarama às 6h e cheguei na hora da consulta." },
  { nome: "Luciana B.", bairro: "Jardim Panorama", texto: "Já fiz essa viagem com vários motoristas. O da Giroto é o mais tranquilo e seguro de todos." },
]

const DEPOIMENTOS_GENERICOS = [
  { nome: "Marcelo G.", bairro: "Centro", texto: "Empresa séria, de família, com décadas em Umuarama. Isso transmite confiança que app nenhum consegue substituir." },
  { nome: "Cláudia R.", bairro: "Zona I", texto: "Atendimento rápido, motorista educado e preço justo. Sempre que preciso de táxi em Umuarama ligo para a Giroto." },
  { nome: "Felipe T.", bairro: "Jardim Aratimbó", texto: "24 horas de verdade. Já liguei de madrugada e em poucos minutos o táxi estava na minha porta." },
]

const DEPOIMENTOS_7LUGARES = [
  { nome: "Família Souza", bairro: "Zona IV", texto: "Fomos para Foz com a família toda, 6 pessoas e malas. O Spin comportou tudo perfeitamente. Viagem ótima." },
  { nome: "Grupo Empresarial", bairro: "Centro", texto: "Levamos a equipe toda para uma capacitação em Maringá. Veículo espaçoso e motorista pontual." },
  { nome: "Vanessa M.", bairro: "Parque San Marino", texto: "Perfeito para grupos. Preço dividido entre todos fica ainda mais em conta do que ir separados." },
]

const DEPOIMENTOS_HOSPITAL = [
  { nome: "Dona Maria", bairro: "Zona II", texto: "Meu marido precisou ir ao hospital de madrugada. O táxi chegou em minutos. Gratidão enorme à Giroto Táxi." },
  { nome: "Roberto C.", bairro: "Jardim Bandeirantes", texto: "Para consultas e exames no Uopeccan, uso sempre. Motorista paciente e atencioso com pacientes." },
  { nome: "Tereza L.", bairro: "Centro", texto: "Serviço essencial para quem não tem carro. 24 horas para qualquer emergência médica em Umuarama." },
]

export const pagesData: PageData[] = [
  {
    slug: "taxi-executivo-umuarama",
    keyword: "táxi executivo em Umuarama",
    title: "Táxi Executivo Umuarama",
    metaTitle: "Táxi Executivo em Umuarama | Giroto Táxi — Alto Padrão 24h",
    metaDescription: "Táxi executivo em Umuarama com veículos de alto padrão. Ideal para reuniões, eventos corporativos e viagens com conforto e pontualidade. Chame agora!",
    h1: "Táxi Executivo em Umuarama — Alto Padrão e Pontualidade",
    intro: "O táxi executivo em Umuarama da Giroto Táxi é a escolha certa para quem precisa de transporte sofisticado, pontual e discreto. Veículos premium, motoristas profissionais e atendimento impecável para executivos, eventos corporativos e ocasiões especiais.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f06, FOTOS.f04],
    testimonials: DEPOIMENTOS_EXECUTIVO,
    features: [
      { icon: "💼", title: "Veículos Premium", desc: "Frota de alto padrão, climatizada e impecável para o seu conforto." },
      { icon: "⏰", title: "Pontualidade Garantida", desc: "Chegamos no horário combinado, sempre. Ideal para reuniões e voos." },
      { icon: "🤫", title: "Discrição Total", desc: "Serviço discreto e profissional para executivos e pessoas públicas." },
      { icon: "📋", title: "Nota Fiscal", desc: "Emitimos nota fiscal para reembolso corporativo." },
    ],
    faq: [
      { q: "O táxi executivo em Umuarama funciona 24 horas?", a: "Sim! Nosso serviço de táxi executivo em Umuarama opera 24 horas por dia, 7 dias por semana, incluindo feriados." },
      { q: "Posso agendar o táxi executivo com antecedência?", a: "Sim, recomendamos agendar via WhatsApp informando data, horário e destino para garantirmos o melhor atendimento." },
      { q: "Vocês emitem nota fiscal para o táxi executivo?", a: "Sim, emitimos nota fiscal para todos os serviços executivos, facilitando o reembolso corporativo." },
      { q: "Qual é o valor do táxi executivo em Umuarama?", a: "Para corridas urbanas executivas usamos o taxímetro oficial. Para viagens intermunicipais, o preço é fechado previamente via WhatsApp." },
    ],
  },
  {
    slug: "taxi-aeroporto-umuarama",
    keyword: "táxi para aeroporto em Umuarama",
    title: "Táxi para Aeroporto Umuarama",
    metaTitle: "Táxi para Aeroporto em Umuarama | Traslado Pontual — Giroto Táxi",
    metaDescription: "Táxi para aeroporto em Umuarama e traslado para o Aeroporto de Maringá. Pontualidade garantida, motorista aguardando. Chame pelo WhatsApp!",
    h1: "Táxi para Aeroporto em Umuarama — Traslado Pontual e Seguro",
    intro: "Precisa de táxi para o aeroporto em Umuarama ou traslado para o Aeroporto Regional de Maringá? A Giroto Táxi garante pontualidade total no seu embarque. Informe o horário do voo e chegue com tranquilidade ao check-in.",
    heroImage: FOTOS.f06,
    galleryImages: [FOTOS.f05, FOTOS.f01],
    testimonials: DEPOIMENTOS_AEROPORTO,
    features: [
      { icon: "✈️", title: "Traslado para Maringá", desc: "Transporte direto de Umuarama para o Aeroporto Regional de Maringá." },
      { icon: "⏰", title: "Pontualidade no Embarque", desc: "Chegamos com antecedência para você não perder o voo." },
      { icon: "🧳", title: "Espaço para Bagagem", desc: "Veículos com porta-malas espaçoso para todas as suas malas." },
      { icon: "📱", title: "Agendamento Fácil", desc: "Agende pelo WhatsApp informando horário do voo e local de embarque." },
    ],
    faq: [
      { q: "Fazem traslado de Umuarama para o aeroporto de Maringá?", a: "Sim! Realizamos traslados frequentes de Umuarama para o Aeroporto Regional de Maringá, com pontualidade garantida." },
      { q: "Com quanto tempo de antecedência devo agendar o táxi para o aeroporto?", a: "Recomendamos agendar com pelo menos 24 horas de antecedência, especialmente para voos matinais." },
      { q: "O táxi espera em caso de atraso do voo?", a: "Sim, monitoramos os voos e nos adaptamos a eventuais atrasos. Entre em contato pelo WhatsApp para atualizações." },
      { q: "Qual o valor do traslado Umuarama–Aeroporto de Maringá?", a: "O traslado Umuarama para o Aeroporto de Maringá tem preço fixo combinado previamente via WhatsApp, sem surpresas." },
    ],
  },
  {
    slug: "taxi-rodoviaria-umuarama",
    keyword: "táxi para rodoviária de Umuarama",
    title: "Táxi para Rodoviária Umuarama",
    metaTitle: "Táxi para Rodoviária de Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi para a rodoviária de Umuarama 24 horas. Chegue no horário certo para pegar seu ônibus. Atendimento imediato pelo WhatsApp!",
    h1: "Táxi para a Rodoviária de Umuarama — Pontual 24 Horas",
    intro: "Não perca o ônibus por falta de transporte. A Giroto Táxi leva e busca na Estação Rodoviária de Umuarama a qualquer hora do dia ou da noite. Atendimento imediato via WhatsApp.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f07, FOTOS.f04],
    testimonials: DEPOIMENTOS_RODOVIARIA,
    features: [
      { icon: "🚌", title: "Direto à Rodoviária", desc: "Te levamos pontualmente à Estação Rodoviária de Umuarama." },
      { icon: "🌙", title: "24 Horas", desc: "Ônibus saindo de madrugada? Estamos disponíveis a qualquer hora." },
      { icon: "📍", title: "Busca em Qualquer Bairro", desc: "Buscamos em qualquer bairro de Umuarama sem taxa extra." },
      { icon: "📱", title: "WhatsApp Imediato", desc: "Resposta em segundos. Agende com antecedência ou chame na hora." },
    ],
    faq: [
      { q: "Vocês buscam na rodoviária de Umuarama de madrugada?", a: "Sim, atendemos 24 horas, incluindo chegadas e saídas de madrugada na rodoviária de Umuarama." },
      { q: "Quanto custa o táxi da rodoviária até o Centro de Umuarama?", a: "O valor é calculado pelo taxímetro oficial. Para orçamento rápido, mande mensagem no WhatsApp com seu destino." },
      { q: "Com quanto tempo de antecedência devo chamar o táxi para a rodoviária?", a: "Recomendamos avisar pelo menos 30 minutos antes. Para horários de madrugada, agende no dia anterior pelo WhatsApp." },
      { q: "Vocês buscam passageiros que chegam de ônibus na rodoviária?", a: "Sim! Buscamos passageiros que chegam de outras cidades na Rodoviária de Umuarama e levamos para qualquer destino na cidade." },
    ],
  },
  {
    slug: "taxi-7-lugares-umuarama",
    keyword: "táxi 7 lugares em Umuarama",
    title: "Táxi 7 Lugares Umuarama",
    metaTitle: "Táxi 7 Lugares em Umuarama | Van para Grupos e Famílias — Giroto Táxi",
    metaDescription: "Táxi 7 lugares em Umuarama para grupos e famílias. Espaço de sobra para bagagem e passageiros. Ideal para viagens, eventos e passeios. Chame agora!",
    h1: "Táxi 7 Lugares em Umuarama — Espaço para Toda a Família",
    intro: "Vai viajar com a família toda, levar a equipe para um evento ou sair com amigos? A Giroto Táxi tem veículos de 7 lugares em Umuarama com espaço de sobra para passageiros e bagagens. Conforto e economia para grupos.",
    heroImage: FOTOS.f02,
    galleryImages: [FOTOS.f09, FOTOS.f04],
    testimonials: DEPOIMENTOS_7LUGARES,
    features: [
      { icon: "👨‍👩‍👧‍👦", title: "Para Toda a Família", desc: "Até 7 passageiros com espaço confortável para todos." },
      { icon: "🧳", title: "Bagageiro Amplo", desc: "Porta-malas espaçoso para malas, sacolas e equipamentos." },
      { icon: "💰", title: "Economia em Grupo", desc: "Dividindo o valor entre os passageiros fica mais barato que ir separado." },
      { icon: "🗺️", title: "Viagens Regionais", desc: "Ideal para viagens entre cidades com grupos grandes." },
    ],
    faq: [
      { q: "Qual veículo de 7 lugares vocês usam em Umuarama?", a: "Utilizamos veículos SUV e minivan com 7 lugares, confortáveis e espaçosos para grupos e famílias." },
      { q: "O táxi 7 lugares faz viagens intermunicipais?", a: "Sim! Realizamos viagens para Maringá, Londrina, Cianorte, Campo Mourão e outras cidades com preço fechado para o grupo." },
      { q: "Preciso agendar com antecedência o táxi 7 lugares?", a: "Recomendamos agendar com pelo menos 24 horas de antecedência para garantir a disponibilidade do veículo de 7 lugares." },
      { q: "Quantas malas cabem no táxi 7 lugares?", a: "Dependendo do modelo, comporta de 4 a 6 malas de tamanho médio além dos 7 passageiros. Para grandes volumes, informe no agendamento." },
    ],
  },
  {
    slug: "taxi-cadeirinha-umuarama",
    keyword: "táxi com cadeirinha em Umuarama",
    title: "Táxi com Cadeirinha Umuarama",
    metaTitle: "Táxi com Cadeirinha em Umuarama | Segurança para Crianças — Giroto Táxi",
    metaDescription: "Táxi com cadeirinha infantil em Umuarama. Transporte seguro para bebês e crianças com cadeira homologada. Agende pelo WhatsApp!",
    h1: "Táxi com Cadeirinha em Umuarama — Segurança para Bebês e Crianças",
    intro: "A segurança do seu filho em primeiro lugar. A Giroto Táxi oferece táxi com cadeirinha infantil homologada em Umuarama para bebês e crianças de todas as idades. Agende com antecedência informando a idade da criança.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f02, FOTOS.f09],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "👶", title: "Cadeirinha Homologada", desc: "Cadeiras infantis certificadas para bebês, crianças e adolescentes." },
      { icon: "🛡️", title: "Máxima Segurança", desc: "Instalação correta e revisada antes de cada viagem com crianças." },
      { icon: "📅", title: "Agende com Antecedência", desc: "Informe a idade da criança ao agendar para prepararmos o equipamento correto." },
      { icon: "👨‍👩‍👧", title: "Toda a Família", desc: "Levamos toda a família com conforto e segurança para qualquer destino." },
    ],
    faq: [
      { q: "Vocês têm cadeirinha para bebê no táxi em Umuarama?", a: "Sim! Disponibilizamos cadeirinha infantil homologada para bebês e crianças. Informe a idade ao agendar para garantirmos o equipamento correto." },
      { q: "É obrigatório usar cadeirinha em táxi?", a: "Sim, o Código de Trânsito Brasileiro exige cadeirinha para crianças menores de 10 anos ou menos de 1,45m de altura em todos os veículos, incluindo táxis." },
      { q: "Com quanto tempo antecedência devo agendar táxi com cadeirinha?", a: "Recomendamos agendar com pelo menos 2 horas de antecedência para garantirmos o equipamento disponível." },
    ],
  },
  {
    slug: "taxi-pet-umuarama",
    keyword: "táxi pet em Umuarama",
    title: "Táxi Pet Umuarama",
    metaTitle: "Táxi Pet em Umuarama | Transporte de Animais — Giroto Táxi",
    metaDescription: "Táxi pet em Umuarama para transporte de cães, gatos e outros animais. Veículo preparado e motorista atencioso. Agende pelo WhatsApp!",
    h1: "Táxi Pet em Umuarama — Transporte Seguro para Seu Animal",
    intro: "Seu pet também merece conforto e segurança. A Giroto Táxi aceita animais de estimação em Umuarama, com veículo preparado e motorista atencioso. Ideal para ir ao veterinário, petshop ou viajar com seu companheiro.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f09, FOTOS.f02],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🐾", title: "Aceita Pets", desc: "Cães, gatos e outros animais de estimação são bem-vindos." },
      { icon: "🏥", title: "Ideal para Veterinário", desc: "Transporte seguro para clínicas veterinárias e petshops de Umuarama." },
      { icon: "🧹", title: "Veículo Preparado", desc: "Proteção no banco e cuidados para manter o veículo limpo." },
      { icon: "📱", title: "Agende com Antecedência", desc: "Informe o tipo e tamanho do pet ao agendar pelo WhatsApp." },
    ],
    faq: [
      { q: "Vocês aceitam cachorros no táxi em Umuarama?", a: "Sim! Aceitamos cães, gatos e outros animais de pequeno e médio porte. Informe o tipo e tamanho do pet ao agendar." },
      { q: "Preciso colocar o pet em caixinha para o táxi?", a: "Para maior segurança do animal e limpeza do veículo, recomendamos o uso de caixa de transporte ou protetor de banco." },
      { q: "O táxi pet vai ao veterinário em Umuarama?", a: "Sim! Levamos e buscamos seu pet em clínicas veterinárias, petshops e qualquer outro destino em Umuarama." },
    ],
  },
  {
    slug: "taxi-hospital-umuarama",
    keyword: "táxi para hospital em Umuarama",
    title: "Táxi para Hospital Umuarama",
    metaTitle: "Táxi para Hospital em Umuarama | Atendimento 24h — Giroto Táxi",
    metaDescription: "Táxi para hospital em Umuarama 24 horas. Transporte rápido e seguro para emergências, consultas e exames. Chame agora pelo WhatsApp!",
    h1: "Táxi para Hospital em Umuarama — Atendimento 24 Horas",
    intro: "Quando a saúde não pode esperar, a Giroto Táxi está disponível 24 horas para levar você ao Hospital Nossa Senhora Aparecida, Uopeccan, UPA e todas as clínicas de Umuarama. Atendimento imediato, inclusive de madrugada.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f10, FOTOS.f02],
    testimonials: DEPOIMENTOS_HOSPITAL,
    features: [
      { icon: "🏥", title: "Todos os Hospitais", desc: "H. Nossa Senhora Aparecida, Uopeccan, UPA e clínicas de Umuarama." },
      { icon: "🌙", title: "24 Horas Emergências", desc: "Disponível inclusive de madrugada para urgências médicas." },
      { icon: "👴", title: "Cuidado com Idosos", desc: "Motoristas pacientes e atenciosos para pacientes e idosos." },
      { icon: "📱", title: "WhatsApp Imediato", desc: "Resposta rápida. Para emergências, ligue direto: (44) 99891-3040." },
    ],
    faq: [
      { q: "Vocês atendem chamados para o hospital de madrugada em Umuarama?", a: "Sim! Atendemos 24 horas por dia, 7 dias por semana, incluindo emergências de madrugada para todos os hospitais de Umuarama." },
      { q: "Vocês levam ao Hospital Nossa Senhora Aparecida em Umuarama?", a: "Sim, atendemos o Hospital Nossa Senhora Aparecida, Uopeccan, UPA e todas as clínicas e laboratórios de Umuarama." },
      { q: "O táxi para hospital em Umuarama aceita pagamento com cartão?", a: "Sim, aceitamos Pix, cartão de débito e crédito, além de dinheiro." },
      { q: "Vocês levam e buscam pacientes em tratamento?", a: "Sim! Muitos pacientes em tratamento contínuo no Uopeccan e outras clínicas usam nosso serviço regularmente. Podemos agendar rotina semanal." },
    ],
  },
  {
    slug: "taxi-umuarama-maringa",
    keyword: "táxi de Umuarama para Maringá",
    title: "Táxi Umuarama para Maringá",
    metaTitle: "Táxi de Umuarama para Maringá | Giroto Táxi — Viagem Segura",
    metaDescription: "Táxi de Umuarama para Maringá com conforto e segurança. Traslado para aeroporto, consultas médicas e negócios. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Maringá — Viagem Segura e Confortável",
    intro: "A rota Umuarama–Maringá pela PR-323 tem 130 km e cerca de 1h30 de viagem. A Giroto Táxi realiza esse trajeto diariamente com preço fixo, motoristas experientes na estrada e veículos confortáveis. Ideal para consultas médicas, negócios e aeroporto.",
    heroImage: FOTOS.f03,
    galleryImages: [FOTOS.f07, FOTOS.f05],
    testimonials: DEPOIMENTOS_MARINGA,
    features: [
      { icon: "🗺️", title: "130 km pela PR-323", desc: "Rota direta Umuarama–Maringá em aproximadamente 1h30." },
      { icon: "💰", title: "Preço Fixo", desc: "Valor combinado antes da viagem. Sem taxímetro, sem surpresa." },
      { icon: "✈️", title: "Aeroporto de Maringá", desc: "Traslado com monitoramento do voo e horário garantido." },
      { icon: "🏥", title: "Consultas Médicas", desc: "Muitos pacientes usam semanalmente para tratamentos em Maringá." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Maringá?", a: "O valor é combinado previamente via WhatsApp com preço fechado. Entre em contato para receber o orçamento atualizado." },
      { q: "Quanto tempo leva o táxi de Umuarama para Maringá?", a: "A viagem leva aproximadamente 1h30, percorrendo 130 km pela PR-323. Em condições normais de tráfego." },
      { q: "Vocês fazem táxi de Umuarama para o aeroporto de Maringá?", a: "Sim! O traslado Umuarama–Aeroporto de Maringá é um dos nossos serviços mais procurados. Monitoramos o voo e garantimos pontualidade." },
      { q: "Vocês buscam passageiros em Maringá para trazer a Umuarama?", a: "Sim, fazemos a rota nos dois sentidos: Umuarama→Maringá e Maringá→Umuarama. Agende pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-umuarama-cianorte",
    keyword: "táxi de Umuarama para Cianorte",
    title: "Táxi Umuarama para Cianorte",
    metaTitle: "Táxi de Umuarama para Cianorte | Giroto Táxi — Viagem Segura",
    metaDescription: "Táxi de Umuarama para Cianorte com conforto e preço justo. Viagem segura para consultas, negócios e passeios. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Cianorte — Viagem Rápida e Segura",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Cianorte com preço fixo, conforto e segurança. São aproximadamente 60 km de trajeto, percorridos em cerca de 1 hora. Ideal para consultas, negócios e passeios.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f03, FOTOS.f07],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "60 km de Distância", desc: "Rota Umuarama–Cianorte em aproximadamente 1 hora." },
      { icon: "💰", title: "Preço Fixo", desc: "Valor fechado antes da viagem, sem surpresas no final." },
      { icon: "🕐", title: "Horário Flexível", desc: "Saída no horário que você precisar, inclusive cedo ou tarde." },
      { icon: "🔄", title: "Ida e Volta", desc: "Fazemos a rota nos dois sentidos. Agende a volta junto." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Cianorte?", a: "O valor é fixo e combinado via WhatsApp antes da viagem. Entre em contato para orçamento atualizado." },
      { q: "Quanto tempo leva o táxi Umuarama–Cianorte?", a: "Aproximadamente 1 hora, percorrendo cerca de 60 km em condições normais de tráfego." },
      { q: "Vocês fazem a volta de Cianorte para Umuarama também?", a: "Sim! Realizamos a rota nos dois sentidos. Você pode agendar ida e volta ou só um trecho." },
    ],
  },
  {
    slug: "taxi-umuarama-goioere",
    keyword: "táxi de Umuarama para Goioerê",
    title: "Táxi Umuarama para Goioerê",
    metaTitle: "Táxi de Umuarama para Goioerê | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Goioerê com segurança e conforto. Preço fechado e motorista experiente. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Goioerê — Conforto e Preço Justo",
    intro: "Precisa ir de Umuarama para Goioerê? A Giroto Táxi realiza essa viagem com preço fechado, motoristas experientes na estrada e veículos confortáveis. Sem taxímetro, sem surpresa.",
    heroImage: FOTOS.f07,
    galleryImages: [FOTOS.f03, FOTOS.f04],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "Rota Direta", desc: "Viagem direta de Umuarama até Goioerê com segurança." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado antes da viagem, sem surpresas." },
      { icon: "🚗", title: "Veículo Confortável", desc: "Ar-condicionado e espaço para bagagem." },
      { icon: "📱", title: "Agende pelo WhatsApp", desc: "Rápido e fácil. Resposta em segundos." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Goioerê?", a: "O preço é fechado e combinado via WhatsApp antes da viagem. Entre em contato para orçamento." },
      { q: "Vocês fazem volta de Goioerê para Umuarama?", a: "Sim, realizamos a rota nos dois sentidos. Agende ida e volta pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-umuarama-cruzeiro-do-oeste",
    keyword: "táxi de Umuarama para Cruzeiro do Oeste",
    title: "Táxi Umuarama para Cruzeiro do Oeste",
    metaTitle: "Táxi de Umuarama para Cruzeiro do Oeste | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Cruzeiro do Oeste. Viagem confortável com preço fechado. Chame pelo WhatsApp!",
    h1: "Táxi de Umuarama para Cruzeiro do Oeste — Viagem Tranquila",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Cruzeiro do Oeste com conforto, pontualidade e preço fechado. Agende pelo WhatsApp e garanta sua viagem.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f07, FOTOS.f03],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "Rota Regional", desc: "Viagem direta de Umuarama para Cruzeiro do Oeste." },
      { icon: "💰", title: "Preço Fixo", desc: "Sem taxímetro. Valor combinado antes de sair." },
      { icon: "🕐", title: "Horário Flexível", desc: "Saia no horário que precisar." },
      { icon: "📱", title: "WhatsApp", desc: "Agende em segundos pelo WhatsApp." },
    ],
    faq: [
      { q: "Fazem táxi de Umuarama para Cruzeiro do Oeste?", a: "Sim! Realizamos essa viagem com preço fechado e combinado previamente pelo WhatsApp." },
      { q: "Vocês buscam em Cruzeiro do Oeste para trazer a Umuarama?", a: "Sim, fazemos os dois sentidos da rota. Entre em contato para agendar." },
    ],
  },
  {
    slug: "taxi-centro-umuarama",
    keyword: "táxi no Centro de Umuarama",
    title: "Táxi no Centro de Umuarama",
    metaTitle: "Táxi no Centro de Umuarama | Corridas Rápidas — Giroto Táxi",
    metaDescription: "Táxi no centro de Umuarama com atendimento imediato. Corridas rápidas para qualquer ponto da cidade. Chame pelo WhatsApp!",
    h1: "Táxi no Centro de Umuarama — Atendimento Imediato",
    intro: "No coração de Umuarama, a Giroto Táxi oferece atendimento imediato para corridas rápidas no centro e para qualquer bairro da cidade. Chame pelo WhatsApp e seu táxi chega em minutos.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Centro de Umuarama", desc: "Atendimento rápido no centro e regiões próximas." },
      { icon: "⚡", title: "Chegada em Minutos", desc: "Motoristas posicionados na região central para atendimento rápido." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível dia e noite, finais de semana e feriados." },
      { icon: "💳", title: "Todas as Formas", desc: "Pix, cartão de débito, crédito ou dinheiro." },
    ],
    faq: [
      { q: "Vocês atendem corridas no centro de Umuarama?", a: "Sim! Atendemos o centro de Umuarama e todos os bairros com corridas rápidas pelo taxímetro oficial." },
      { q: "Qual o valor mínimo de corrida no centro de Umuarama?", a: "As corridas urbanas seguem o taxímetro oficial de Umuarama. Para uma estimativa, mande mensagem no WhatsApp com origem e destino." },
    ],
  },
  {
    slug: "taxi-noturno-umuarama",
    keyword: "táxi noturno em Umuarama",
    title: "Táxi Noturno Umuarama",
    metaTitle: "Táxi Noturno em Umuarama | Disponível de Madrugada — Giroto Táxi",
    metaDescription: "Táxi noturno em Umuarama disponível de madrugada, fins de semana e feriados. Volte de festas e eventos com segurança. Chame agora!",
    h1: "Táxi Noturno em Umuarama — De Madrugada Também Atendemos",
    intro: "Voltando de festa, evento ou precisando de táxi de madrugada em Umuarama? A Giroto Táxi opera 24 horas, inclusive nos horários mais difíceis de encontrar transporte. Sua segurança na volta para casa.",
    heroImage: FOTOS.f08,
    galleryImages: [FOTOS.f01, FOTOS.f04],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🌙", title: "Madrugada", desc: "Atendemos de madrugada quando outros serviços param." },
      { icon: "🎉", title: "Volta de Festas", desc: "Transporte seguro na saída de festas, casamentos e eventos." },
      { icon: "🛡️", title: "Segurança Total", desc: "Motoristas credenciados, veículos identificados. Chame com confiança." },
      { icon: "📱", title: "WhatsApp 24h", desc: "Mande mensagem a qualquer hora. Resposta imediata." },
    ],
    faq: [
      { q: "Vocês atendem táxi de madrugada em Umuarama?", a: "Sim! Atendemos 24 horas, incluindo madrugada, finais de semana e feriados em Umuarama." },
      { q: "O valor do táxi noturno é mais caro em Umuarama?", a: "As corridas noturnas seguem a tabela oficial do taxímetro de Umuarama, que pode ter acréscimo noturno conforme regulamentação municipal." },
      { q: "É seguro chamar táxi de madrugada em Umuarama?", a: "Sim! Nossos motoristas são todos credenciados e licenciados pela prefeitura de Umuarama. Veículos identificados com número de alvará." },
    ],
  },
  {
    slug: "taxi-casamento-umuarama",
    keyword: "táxi para casamento em Umuarama",
    title: "Táxi para Casamento Umuarama",
    metaTitle: "Táxi para Casamento em Umuarama | Transporte de Noivos — Giroto Táxi",
    metaDescription: "Táxi para casamento em Umuarama. Transporte dos noivos, padrinhos e convidados com pontualidade e elegância. Agende pelo WhatsApp!",
    h1: "Táxi para Casamento em Umuarama — Elegância e Pontualidade",
    intro: "O dia mais especial da sua vida merece o melhor transporte. A Giroto Táxi oferece serviço de táxi para casamentos em Umuarama com veículos impecáveis, motoristas bem apresentados e pontualidade absoluta para noivos, padrinhos e convidados.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f06, FOTOS.f04],
    testimonials: DEPOIMENTOS_EXECUTIVO,
    features: [
      { icon: "💍", title: "Para Noivos", desc: "Transporte especial para os noivos no dia do casamento." },
      { icon: "👔", title: "Motorista Apresentável", desc: "Motoristas bem vestidos e preparados para ocasiões especiais." },
      { icon: "🚗", title: "Veículo Impecável", desc: "Carro limpo, cheiroso e em perfeito estado para o grande dia." },
      { icon: "⏰", title: "Pontualidade Absoluta", desc: "Chegamos antes do horário combinado. Sem atrasos no seu casamento." },
    ],
    faq: [
      { q: "Vocês fazem táxi para casamento em Umuarama?", a: "Sim! Oferecemos transporte para casamentos em Umuarama, atendendo noivos, padrinhos, familiares e convidados." },
      { q: "Com quanto tempo devo contratar o táxi para meu casamento?", a: "Recomendamos agendar com pelo menos 1 semana de antecedência para garantir disponibilidade na data do casamento." },
    ],
  },
  {
    slug: "taxi-formatura-umuarama",
    keyword: "táxi para formatura em Umuarama",
    title: "Táxi para Formatura Umuarama",
    metaTitle: "Táxi para Formatura em Umuarama | Transporte — Giroto Táxi",
    metaDescription: "Táxi para formatura em Umuarama. Chegue com estilo e pontualidade na sua cerimônia de formatura. Agende pelo WhatsApp!",
    h1: "Táxi para Formatura em Umuarama — Chegue com Estilo",
    intro: "Sua formatura é uma conquista que merece ser celebrada com estilo. A Giroto Táxi oferece transporte para formaturas em Umuarama com veículos limpos, motoristas apresentáveis e pontualidade garantida.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f08, FOTOS.f04],
    testimonials: DEPOIMENTOS_EXECUTIVO,
    features: [
      { icon: "🎓", title: "Dia Especial", desc: "Transporte à altura da sua conquista acadêmica." },
      { icon: "🚗", title: "Veículo Impecável", desc: "Carro limpo e preparado para a ocasião." },
      { icon: "📸", title: "Chegue com Estilo", desc: "Motorista apresentável para as fotos do momento." },
      { icon: "⏰", title: "Sem Atrasos", desc: "Pontualidade para você não perder nenhum momento." },
    ],
    faq: [
      { q: "Vocês fazem táxi para formatura em Umuarama?", a: "Sim! Transportamos formandos e familiares para cerimônias de formatura em Umuarama e região." },
      { q: "Vocês atendem grupos de formandos?", a: "Sim, temos veículos de até 7 lugares para grupos. Para turmas maiores, podemos coordenar múltiplos veículos." },
    ],
  },
  {
    slug: "taxi-empresas-umuarama",
    keyword: "táxi para empresas em Umuarama",
    title: "Táxi para Empresas Umuarama",
    metaTitle: "Táxi para Empresas em Umuarama | Transporte Corporativo — Giroto Táxi",
    metaDescription: "Táxi para empresas em Umuarama. Transporte corporativo com nota fiscal, pontualidade e frota preparada. Fale pelo WhatsApp!",
    h1: "Táxi para Empresas em Umuarama — Transporte Corporativo",
    intro: "A Giroto Táxi atende empresas de Umuarama com serviço de transporte corporativo: nota fiscal, pontualidade, veículos de alto padrão e contratos mensais. Atendemos CVale, Capacol, Umuarama Indústria e demais empresas da região.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f06, FOTOS.f08],
    testimonials: DEPOIMENTOS_EXECUTIVO,
    features: [
      { icon: "📋", title: "Nota Fiscal", desc: "Emissão de nota fiscal para todas as corridas corporativas." },
      { icon: "🤝", title: "Contrato Mensal", desc: "Planos mensais para empresas com demanda regular." },
      { icon: "💼", title: "Alto Padrão", desc: "Frota executiva para receber clientes e diretores." },
      { icon: "⏰", title: "Pontualidade", desc: "Compromisso com horários para não comprometer reuniões." },
    ],
    faq: [
      { q: "Vocês atendem empresas em Umuarama com nota fiscal?", a: "Sim! Emitimos nota fiscal para todas as corridas corporativas, facilitando o controle financeiro e reembolso." },
      { q: "É possível fazer contrato mensal de táxi para empresa em Umuarama?", a: "Sim, oferecemos planos mensais para empresas com demanda regular de transporte. Entre em contato pelo WhatsApp para negociar." },
    ],
  },
  {
    slug: "taxi-nota-fiscal-umuarama",
    keyword: "táxi com nota fiscal em Umuarama",
    title: "Táxi com Nota Fiscal Umuarama",
    metaTitle: "Táxi com Nota Fiscal em Umuarama | Corridas Corporativas — Giroto Táxi",
    metaDescription: "Táxi com nota fiscal em Umuarama para empresas e reembolso corporativo. Serviço profissional com documentação completa. Fale pelo WhatsApp!",
    h1: "Táxi com Nota Fiscal em Umuarama — Para Empresas e Reembolso",
    intro: "Precisa de táxi com nota fiscal em Umuarama para reembolso corporativo ou controle financeiro? A Giroto Táxi emite nota fiscal para todas as corridas e viagens, atendendo o padrão exigido por empresas e contabilidades.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f06, FOTOS.f08],
    testimonials: DEPOIMENTOS_EXECUTIVO,
    features: [
      { icon: "📋", title: "Nota Fiscal", desc: "NF emitida para todas as corridas com documentação correta." },
      { icon: "💼", title: "Reembolso Fácil", desc: "Documentação aceita por todas as empresas para reembolso." },
      { icon: "🏢", title: "Para Empresas", desc: "Ideal para empresas que precisam de controle de despesas." },
      { icon: "✅", title: "Regularizado", desc: "Táxi licenciado e regularizado pela prefeitura de Umuarama." },
    ],
    faq: [
      { q: "Vocês emitem nota fiscal para corridas de táxi em Umuarama?", a: "Sim! Emitimos nota fiscal para corridas urbanas e viagens intermunicipais, atendendo às exigências corporativas." },
      { q: "A nota fiscal do táxi de Umuarama é aceita para reembolso?", a: "Sim, nossa documentação atende os padrões exigidos para reembolso corporativo." },
    ],
  },
  {
    slug: "taxi-idosos-umuarama",
    keyword: "táxi para idosos em Umuarama",
    title: "Táxi para Idosos Umuarama",
    metaTitle: "Táxi para Idosos em Umuarama | Cuidado e Atenção — Giroto Táxi",
    metaDescription: "Táxi para idosos em Umuarama com motoristas pacientes e veículos confortáveis. Ideal para consultas médicas e deslocamentos. Chame agora!",
    h1: "Táxi para Idosos em Umuarama — Cuidado e Atenção",
    intro: "Motoristas pacientes, veículos confortáveis e atendimento humano. A Giroto Táxi oferece transporte especial para idosos em Umuarama, seja para consultas médicas, compras ou qualquer deslocamento com segurança e conforto.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f10, FOTOS.f02],
    testimonials: DEPOIMENTOS_HOSPITAL,
    features: [
      { icon: "👴", title: "Motoristas Pacientes", desc: "Equipe treinada para atender idosos com cuidado e paciência." },
      { icon: "🚗", title: "Veículo Confortável", desc: "Entrada e saída facilitadas, ar-condicionado e banco confortável." },
      { icon: "🏥", title: "Consultas Médicas", desc: "Levamos ao médico, hospital, laboratório e farmácias de Umuarama." },
      { icon: "📱", title: "Familiar Pode Agendar", desc: "Familiar pode agendar pelo WhatsApp para o idoso." },
    ],
    faq: [
      { q: "Vocês têm táxi especial para idosos em Umuarama?", a: "Sim! Nossos motoristas são habituados a atender idosos com paciência e cuidado em Umuarama." },
      { q: "Posso agendar táxi para meu pai idoso pelo WhatsApp?", a: "Sim! Familiar pode agendar pelo WhatsApp informando nome, endereço e destino. O motorista vai buscar o idoso na porta." },
    ],
  },
  {
    slug: "taxi-farmacia-umuarama",
    keyword: "táxi para farmácia em Umuarama",
    title: "Táxi para Farmácia Umuarama",
    metaTitle: "Táxi para Farmácia em Umuarama | 24h — Giroto Táxi",
    metaDescription: "Táxi para farmácia em Umuarama 24 horas. Busca de medicamentos urgentes a qualquer hora. Chame pelo WhatsApp!",
    h1: "Táxi para Farmácia em Umuarama — Medicamentos Urgentes 24h",
    intro: "Precisa de medicamento urgente de madrugada? A Giroto Táxi leva até a farmácia de plantão em Umuarama a qualquer hora. Rápido, seguro e disponível quando você mais precisa.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f10, FOTOS.f09],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "💊", title: "Farmácias 24h", desc: "Levamos às farmácias de plantão em Umuarama a qualquer hora." },
      { icon: "🌙", title: "Madrugada", desc: "Disponível quando as farmácias de plantão estão abertas." },
      { icon: "⚡", title: "Atendimento Rápido", desc: "Para urgências, ligamos e o táxi chega em minutos." },
      { icon: "👴", title: "Para Idosos", desc: "Especialmente útil para idosos que precisam de remédios urgentes." },
    ],
    faq: [
      { q: "Vocês levam para farmácia de plantão em Umuarama?", a: "Sim! Levamos para qualquer farmácia de Umuarama, incluindo as de plantão 24 horas." },
      { q: "Atendem de madrugada para busca de remédio em Umuarama?", a: "Sim, atendemos 24 horas, inclusive madrugada para medicamentos urgentes." },
    ],
  },
  {
    slug: "taxi-umuarama-londrina",
    keyword: "táxi de Umuarama para Londrina",
    title: "Táxi Umuarama para Londrina",
    metaTitle: "Táxi de Umuarama para Londrina | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Londrina com conforto e segurança. Preço fechado e motorista experiente. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Londrina — Viagem Longa com Conforto",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Londrina percorrendo aproximadamente 230 km. Com preço fixo combinado, motoristas experientes em rodovias e veículos confortáveis para a jornada de cerca de 3 horas.",
    heroImage: FOTOS.f07,
    galleryImages: [FOTOS.f03, FOTOS.f06],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "230 km de Viagem", desc: "Trajeto Umuarama–Londrina em aproximadamente 3 horas." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado antes de sair. Sem surpresas no final." },
      { icon: "🚗", title: "Conforto na Estrada", desc: "Ar-condicionado, música e descanso durante o trajeto." },
      { icon: "✈️", title: "Aeroporto de Londrina", desc: "Traslado para o Aeroporto Governador José Richa." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Londrina?", a: "O valor é fechado e combinado via WhatsApp antes da viagem. Entre em contato para orçamento atualizado." },
      { q: "Quanto tempo leva a viagem Umuarama–Londrina de táxi?", a: "Aproximadamente 3 horas, percorrendo cerca de 230 km pelas rodovias PR-323 e BR-369." },
      { q: "Vocês vão ao aeroporto de Londrina saindo de Umuarama?", a: "Sim! Fazemos o traslado direto de Umuarama para o Aeroporto de Londrina com preço fechado." },
    ],
  },
  {
    slug: "taxi-umuarama-curitiba",
    keyword: "táxi de Umuarama para Curitiba",
    title: "Táxi Umuarama para Curitiba",
    metaTitle: "Táxi de Umuarama para Curitiba | Giroto Táxi — Longa Distância",
    metaDescription: "Táxi de Umuarama para Curitiba. Viagem longa e confortável com motorista experiente e preço fechado. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Curitiba — Viagem Longa com Segurança",
    intro: "A Giroto Táxi realiza viagens de Umuarama para Curitiba, percorrendo aproximadamente 460 km em cerca de 5 horas. Preço fixo, motorista experiente em rodovias de longa distância e veículo totalmente preparado.",
    heroImage: FOTOS.f01,
    galleryImages: [FOTOS.f07, FOTOS.f03],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "460 km", desc: "Viagem Umuarama–Curitiba em aproximadamente 5 horas." },
      { icon: "💰", title: "Preço Fechado", desc: "Valor combinado antes da viagem, sem taxímetro." },
      { icon: "🚗", title: "Longa Distância", desc: "Motoristas experientes em viagens de longa distância." },
      { icon: "✈️", title: "Aeroporto Afonso Pena", desc: "Traslado direto para o aeroporto internacional de Curitiba." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Curitiba?", a: "O valor é fechado e combinado via WhatsApp. É uma viagem longa, portanto o preço é calculado por km rodado + pedágios. Entre em contato para orçamento." },
      { q: "Quanto tempo leva a viagem de táxi Umuarama–Curitiba?", a: "Aproximadamente 5 horas, percorrendo cerca de 460 km." },
      { q: "Vocês vão ao aeroporto de Curitiba saindo de Umuarama?", a: "Sim! Fazemos o traslado Umuarama–Aeroporto Afonso Pena com preço fechado e motorista experiente." },
    ],
  },
  {
    slug: "taxi-umuarama-campo-mourao",
    keyword: "táxi de Umuarama para Campo Mourão",
    title: "Táxi Umuarama para Campo Mourão",
    metaTitle: "Táxi de Umuarama para Campo Mourão | Giroto Táxi",
    metaDescription: "Táxi de Umuarama para Campo Mourão. Viagem segura com preço fechado. Agende pelo WhatsApp!",
    h1: "Táxi de Umuarama para Campo Mourão — Viagem Segura",
    intro: "Precisa ir de Umuarama para Campo Mourão? A Giroto Táxi realiza essa viagem de aproximadamente 150 km com preço fixo e motorista experiente. Conforto e segurança do início ao fim.",
    heroImage: FOTOS.f07,
    galleryImages: [FOTOS.f03, FOTOS.f04],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "🗺️", title: "150 km", desc: "Rota Umuarama–Campo Mourão em cerca de 2 horas." },
      { icon: "💰", title: "Preço Fixo", desc: "Sem taxímetro. Valor combinado antes da saída." },
      { icon: "🔄", title: "Ida e Volta", desc: "Realizamos o trajeto nos dois sentidos." },
      { icon: "📱", title: "Agende pelo WhatsApp", desc: "Orçamento e agendamento rápidos." },
    ],
    faq: [
      { q: "Quanto custa o táxi de Umuarama para Campo Mourão?", a: "Preço fixo combinado via WhatsApp. Entre em contato para orçamento atualizado." },
      { q: "Vocês fazem a volta de Campo Mourão para Umuarama?", a: "Sim! Realizamos a rota nos dois sentidos. Agende pelo WhatsApp." },
    ],
  },
  {
    slug: "corridas-taxi-umuarama",
    keyword: "corridas de táxi em Umuarama",
    title: "Corridas de Táxi em Umuarama",
    metaTitle: "Corridas de Táxi em Umuarama | Rápido e Seguro — Giroto Táxi",
    metaDescription: "Corridas de táxi em Umuarama 24 horas. Transporte rápido e seguro para qualquer destino na cidade. Chame pelo WhatsApp!",
    h1: "Corridas de Táxi em Umuarama — Rápido, Seguro e 24 Horas",
    intro: "Precisa de táxi em Umuarama agora? A Giroto Táxi realiza corridas rápidas para qualquer bairro da cidade, 24 horas por dia. Taxímetro oficial, motoristas licenciados e atendimento imediato pelo WhatsApp.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f01, FOTOS.f10],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "⚡", title: "Atendimento Imediato", desc: "Motorista disponível para corridas em qualquer bairro de Umuarama." },
      { icon: "📍", title: "Todos os Bairros", desc: "Centro, Zonas I a IV, Jardim Panorama, Parque Tarumã e todos os bairros." },
      { icon: "📊", title: "Taxímetro Oficial", desc: "Corridas pelo taxímetro regulamentado pela prefeitura de Umuarama." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora, todos os dias da semana." },
    ],
    faq: [
      { q: "Como chamar táxi em Umuarama?", a: "Pelo WhatsApp (44) 99891-3040 ou ligando (44) 98416-0050. Informe seu endereço e o motorista chega em minutos." },
      { q: "Qual o valor da corrida de táxi em Umuarama?", a: "As corridas urbanas seguem o taxímetro oficial regulamentado pela Prefeitura de Umuarama. Para estimativa, envie origem e destino pelo WhatsApp." },
      { q: "O táxi em Umuarama funciona de madrugada?", a: "Sim! A Giroto Táxi atende 24 horas, inclusive de madrugada e em feriados." },
      { q: "Vocês aceitam cartão no táxi em Umuarama?", a: "Sim! Aceitamos Pix, cartão de débito, crédito e dinheiro." },
    ],
  },
  {
    slug: "taxi-jardim-panorama-umuarama",
    keyword: "táxi no Jardim Panorama Umuarama",
    title: "Táxi Jardim Panorama Umuarama",
    metaTitle: "Táxi no Jardim Panorama Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi no Jardim Panorama em Umuarama com atendimento rápido 24 horas. Corridas e viagens pelo WhatsApp!",
    h1: "Táxi no Jardim Panorama em Umuarama — Atendimento Imediato",
    intro: "Motoristas da Giroto Táxi atendem o Jardim Panorama e toda a região com rapidez e eficiência. Corridas urbanas 24 horas e viagens intermunicipais com preço fixo.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f10, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Jardim Panorama", desc: "Atendimento rápido em todo o Jardim Panorama." },
      { icon: "⚡", title: "Chegada Rápida", desc: "Motoristas próximos ao bairro para atendimento imediato." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora no Jardim Panorama." },
      { icon: "📱", title: "WhatsApp", desc: "Chame agora pelo WhatsApp e receba atendimento imediato." },
    ],
    faq: [
      { q: "Vocês atendem táxi no Jardim Panorama em Umuarama?", a: "Sim! Atendemos o Jardim Panorama e toda a cidade de Umuarama, 24 horas por dia." },
      { q: "Quanto custa o táxi do Jardim Panorama até o centro de Umuarama?", a: "O valor segue o taxímetro oficial. Para estimativa, envie a rota pelo WhatsApp." },
    ],
  },
  {
    slug: "taxi-zona-1-umuarama",
    keyword: "táxi na Zona 1 de Umuarama",
    title: "Táxi Zona 1 Umuarama",
    metaTitle: "Táxi na Zona 1 de Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi na Zona 1 de Umuarama com atendimento imediato 24 horas. Corridas e viagens. Chame pelo WhatsApp!",
    h1: "Táxi na Zona 1 de Umuarama — 24 Horas",
    intro: "A Giroto Táxi atende a Zona 1 de Umuarama com corridas rápidas e viagens intermunicipais. Taxímetro oficial, motoristas licenciados e atendimento imediato.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Zona 1 Umuarama", desc: "Atendimento rápido em toda a Zona 1." },
      { icon: "⚡", title: "Chegada em Minutos", desc: "Motoristas posicionados para atendimento ágil." },
      { icon: "🕐", title: "24 Horas", desc: "Táxi disponível na Zona 1 a qualquer hora." },
      { icon: "📱", title: "WhatsApp", desc: "Chame agora: (44) 99891-3040." },
    ],
    faq: [
      { q: "Vocês atendem táxi na Zona 1 de Umuarama?", a: "Sim! A Giroto Táxi atende a Zona 1 e toda Umuarama, 24 horas por dia." },
    ],
  },
  {
    slug: "taxi-zona-2-umuarama",
    keyword: "táxi na Zona 2 de Umuarama",
    title: "Táxi Zona 2 Umuarama",
    metaTitle: "Táxi na Zona 2 de Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi na Zona 2 de Umuarama com atendimento imediato 24 horas. Corridas e viagens. Chame pelo WhatsApp!",
    h1: "Táxi na Zona 2 de Umuarama — 24 Horas",
    intro: "Atendimento de táxi na Zona 2 de Umuarama com rapidez e segurança. Corridas urbanas e viagens intermunicipais com preço justo.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f02],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Zona 2 Umuarama", desc: "Cobertura completa em toda a Zona 2." },
      { icon: "⚡", title: "Atendimento Rápido", desc: "Motoristas disponíveis para chegada em minutos." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível dia e noite na Zona 2." },
      { icon: "📱", title: "WhatsApp", desc: "Atendimento imediato pelo WhatsApp." },
    ],
    faq: [
      { q: "Vocês atendem táxi na Zona 2 de Umuarama?", a: "Sim! Atendemos a Zona 2 e toda a cidade de Umuarama 24 horas." },
    ],
  },
  {
    slug: "taxi-parque-taruma-umuarama",
    keyword: "táxi no Parque Tarumã Umuarama",
    title: "Táxi Parque Tarumã Umuarama",
    metaTitle: "Táxi no Parque Tarumã Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi no Parque Tarumã em Umuarama 24 horas. Atendimento rápido para corridas e viagens. Chame pelo WhatsApp!",
    h1: "Táxi no Parque Tarumã em Umuarama — Atendimento 24h",
    intro: "A Giroto Táxi atende o Parque Tarumã e região com motoristas próximos e atendimento imediato. Corridas rápidas 24 horas.",
    heroImage: FOTOS.f04,
    galleryImages: [FOTOS.f10, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Parque Tarumã", desc: "Atendimento rápido em todo o Parque Tarumã." },
      { icon: "⚡", title: "Chegada Ágil", desc: "Motoristas disponíveis para atendimento imediato." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora no Parque Tarumã." },
      { icon: "📱", title: "WhatsApp", desc: "Chame agora pelo WhatsApp." },
    ],
    faq: [
      { q: "Vocês atendem táxi no Parque Tarumã em Umuarama?", a: "Sim! Atendemos o Parque Tarumã e toda Umuarama 24 horas." },
    ],
  },
  {
    slug: "taxi-jardim-aratimbo-umuarama",
    keyword: "táxi no Jardim Aratimbó Umuarama",
    title: "Táxi Jardim Aratimbó Umuarama",
    metaTitle: "Táxi no Jardim Aratimbó Umuarama | Giroto Táxi 24h",
    metaDescription: "Táxi no Jardim Aratimbó em Umuarama 24 horas. Corridas rápidas e viagens. Chame pelo WhatsApp!",
    h1: "Táxi no Jardim Aratimbó em Umuarama — 24 Horas",
    intro: "A Giroto Táxi atende o Jardim Aratimbó e toda Umuarama com corridas urbanas e viagens intermunicipais. Atendimento imediato pelo WhatsApp.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f09],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📍", title: "Jardim Aratimbó", desc: "Cobertura em todo o Jardim Aratimbó." },
      { icon: "⚡", title: "Rápido", desc: "Motoristas próximos para atendimento ágil." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora." },
      { icon: "📱", title: "WhatsApp", desc: "Chame agora: (44) 99891-3040." },
    ],
    faq: [
      { q: "Vocês atendem táxi no Jardim Aratimbó em Umuarama?", a: "Sim! Atendemos o Jardim Aratimbó e toda Umuarama 24 horas por dia." },
    ],
  },
  {
    slug: "chamar-taxi-umuarama",
    keyword: "chamar táxi em Umuarama",
    title: "Chamar Táxi Umuarama",
    metaTitle: "Chamar Táxi em Umuarama | Giroto Táxi — WhatsApp Imediato",
    metaDescription: "Saiba como chamar táxi em Umuarama pelo WhatsApp ou telefone. Giroto Táxi 24 horas. Atendimento imediato!",
    h1: "Como Chamar Táxi em Umuarama — WhatsApp Imediato",
    intro: "A forma mais rápida de chamar táxi em Umuarama é pelo WhatsApp da Giroto Táxi. Basta enviar uma mensagem com seu endereço e o motorista mais próximo confirma em segundos.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📱", title: "Pelo WhatsApp", desc: "Mande mensagem no (44) 99891-3040 com seu endereço." },
      { icon: "📞", title: "Pelo Telefone", desc: "Ligue (44) 98416-0050 para atendimento imediato." },
      { icon: "⚡", title: "Resposta Rápida", desc: "Confirmação em segundos. Motorista chega em minutos." },
      { icon: "🕐", title: "24 Horas", desc: "Disponível a qualquer hora em Umuarama." },
    ],
    faq: [
      { q: "Como chamar táxi em Umuarama pelo WhatsApp?", a: "Envie mensagem para (44) 99891-3040 informando seu endereço e destino. O motorista confirma em segundos." },
      { q: "Qual o telefone do táxi em Umuarama?", a: "Os telefones da Giroto Táxi em Umuarama são: (44) 99891-3040 (WhatsApp) e (44) 98416-0050." },
      { q: "Quanto tempo o táxi demora para chegar em Umuarama?", a: "Em média 5 a 10 minutos após o contato, dependendo do bairro e horário." },
    ],
  },
  {
    slug: "telefone-taxi-umuarama",
    keyword: "telefone táxi Umuarama",
    title: "Telefone Táxi Umuarama",
    metaTitle: "Telefone Táxi Umuarama | Giroto Táxi — (44) 99891-3040",
    metaDescription: "Telefone do táxi em Umuarama: (44) 99891-3040. Giroto Táxi 24 horas. Ligue ou mande WhatsApp agora!",
    h1: "Telefone do Táxi em Umuarama — (44) 99891-3040",
    intro: "O telefone da Giroto Táxi em Umuarama é (44) 99891-3040 (WhatsApp) e (44) 98416-0050. Atendimento 24 horas, todos os dias. Ligue ou mande mensagem e seu táxi chega em minutos.",
    heroImage: FOTOS.f10,
    galleryImages: [FOTOS.f04, FOTOS.f01],
    testimonials: DEPOIMENTOS_GENERICOS,
    features: [
      { icon: "📞", title: "(44) 99891-3040", desc: "WhatsApp principal. Resposta em segundos." },
      { icon: "📞", title: "(44) 98416-0050", desc: "Linha de voz. Atendimento imediato." },
      { icon: "🕐", title: "24 Horas", desc: "Ligamos e atendemos a qualquer hora." },
      { icon: "📍", title: "Toda Umuarama", desc: "Atendemos todos os bairros de Umuarama." },
    ],
    faq: [
      { q: "Qual o número do táxi em Umuarama?", a: "O telefone da Giroto Táxi em Umuarama é (44) 99891-3040 (WhatsApp) e (44) 98416-0050." },
      { q: "O táxi de Umuarama tem WhatsApp?", a: "Sim! O WhatsApp da Giroto Táxi é (44) 99891-3040. Mande mensagem e receba resposta em segundos." },
    ],
  },
]
